# Lendo os resultados

In [1]:
import sys
import os

project_root = os.path.abspath(os.path.join(os.getcwd(), ".."))  

if project_root not in sys.path:
    sys.path.append(project_root)

print("Project Root:", project_root)

Project Root: /home/vtcfreitas/RLCOVID_folder/RL-COVID-Events

In [2]:
import random

import pandas as pd
import numpy as np

from utils import load_edges

In [3]:
pca = pd.read_parquet('../EvaluationResults/Covid-19Vaccine_dataset/comparison_results_PCA.parquet')
tsne = pd.read_parquet('../EvaluationResults/Covid-19Vaccine_dataset/comparison_results_TSNE.parquet')
tsne_pca = pd.read_parquet('../EvaluationResults/Covid-19Vaccine_dataset/comparison_results_TSNE+PCA.parquet')
umap = pd.read_parquet('../EvaluationResults/Covid-19Vaccine_dataset/comparison_results_UMAP.parquet')

In [4]:
def f1_score(precision: float, recall: float)-> float:
  return 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0

In [5]:
def find_best_compared_graphs(df: np.ndarray, metric: str):
    best_graphs = {}
    for ref_graph in df['Reference Graph'].unique():
        filtered = df[df['Reference Graph'] == ref_graph]
        best_match = filtered[filtered[metric] == filtered[metric].max()]
        best_graphs[ref_graph] = best_match['Compared Graph'].tolist()

    unique_winners = set(graph for graphs in best_graphs.values() for graph in graphs)
    
    return best_graphs, unique_winners

# Análise Exploratória dos comparativos

## Grafos gerados

### Consistency

In [7]:
consistency_path = '../GeneratedGraphs/Consistency/Covid-19Vaccine_dataset'
consistency_file = random.choice(os.listdir(consistency_path))

In [8]:
consistency_file

'consistency_edges_1_1_67.pkl'

In [ ]:
consistency_graph = load_edges(consistency_path,consistency_file)

In [10]:
len(consistency_graph)

2774

### t-SNE

In [12]:
tsne_path = '../GeneratedGraphs/TSNE/Covid-19Vaccine_dataset'
tsne_file = random.choice(os.listdir(tsne_path))

In [13]:
tsne_file

'tsne_edges_23_50_pca.pkl'

In [ ]:
tsne_graph = load_edges(tsne_path,tsne_file)

In [15]:
len(tsne_graph)

230000

### PCA

In [16]:
import random

In [17]:
pca_path = '../GeneratedGraphs/PCA/Covid-19Vaccine_dataset'
pca_file = random.choice(os.listdir(pca_path))

In [18]:
pca_file

'pca_edges_34_whitened.pkl'

In [19]:
from utils import load_edges

pca_graph = load_edges(pca_path,pca_file)

In [20]:
len(pca_graph)

340000

### UMAP

In [21]:
umap_path = '../GeneratedGraphs/UMAP/Covid-19Vaccine_dataset'
umap_file = random.choice(os.listdir(umap_path))

In [22]:
umap_file

'umap_edges_56_101_0.0_spectral.pkl'

In [23]:
umap_graph = load_edges(umap_path,umap_file)

In [24]:
len(umap_graph)

325240

## Comparação com o gráfico de consistência

### PCA

In [25]:
pca

,Reference Graph,Compared Graph,Precision,Recall
0,consistency_edges_100_100_1.pkl,pca_edges_1.pkl,0.115500,0.037819
1,consistency_edges_100_100_1.pkl,pca_edges_100.pkl,0.007219,0.236379
2,consistency_edges_100_100_1.pkl,pca_edges_100_whitened.pkl,0.007221,0.236444
3,consistency_edges_100_100_1.pkl,pca_edges_12.pkl,0.031550,0.123969
4,consistency_edges_100_100_1.pkl,pca_edges_12_whitened.pkl,0.031625,0.124263
...,...,...,...,...
19995,consistency_edges_89_89_89.pkl,pca_edges_67_whitened.pkl,0.015664,0.168443
19996,consistency_edges_89_89_89.pkl,pca_edges_78.pkl,0.014231,0.178153
19997,consistency_edges_89_89_89.pkl,pca_edges_78_whitened.pkl,0.014224,0.178073
19998,consistency_edges_89_89_89.pkl,pca_edges_89.pkl,0.013101,0.187141
19999,consistency_edges_89_89_89.pkl,pca_edges_89_whitened.pkl,0.013131,0.187574

In [26]:
pca['F1_score'] = pca.apply(lambda row: f1_score(row['Precision'], row['Recall']), axis=1)
pca

,Reference Graph,Compared Graph,Precision,Recall,F1_score
0,consistency_edges_100_100_1.pkl,pca_edges_1.pkl,0.115500,0.037819,0.056981
1,consistency_edges_100_100_1.pkl,pca_edges_100.pkl,0.007219,0.236379,0.014010
2,consistency_edges_100_100_1.pkl,pca_edges_100_whitened.pkl,0.007221,0.236444,0.014014
3,consistency_edges_100_100_1.pkl,pca_edges_12.pkl,0.031550,0.123969,0.050299
4,consistency_edges_100_100_1.pkl,pca_edges_12_whitened.pkl,0.031625,0.124263,0.050418
...,...,...,...,...,...
19995,consistency_edges_89_89_89.pkl,pca_edges_67_whitened.pkl,0.015664,0.168443,0.028663
19996,consistency_edges_89_89_89.pkl,pca_edges_78.pkl,0.014231,0.178153,0.026356
19997,consistency_edges_89_89_89.pkl,pca_edges_78_whitened.pkl,0.014224,0.178073,0.026344
19998,consistency_edges_89_89_89.pkl,pca_edges_89.pkl,0.013101,0.187141,0.024488
19999,consistency_edges_89_89_89.pkl,pca_edges_89_whitened.pkl,0.013131,0.187574,0.024545

In [27]:
pca.describe()

          Precision        Recall      F1_score
count  20000.000000  20000.000000  20000.000000
mean       0.028381      0.263764      0.033489
std        0.041453      0.121184      0.024233
min        0.000227      0.025196      0.000454
25%        0.009062      0.190668      0.017602
50%        0.013239      0.253238      0.025119
75%        0.024162      0.328900      0.042862
max        0.184500      0.797203      0.171450

In [28]:
pca[pca.Precision == pca.Precision.max()]

,Reference Graph,Compared Graph,Precision,Recall,F1_score
20,consistency_edges_100_100_100.pkl,pca_edges_1.pkl,0.1845,0.025292,0.044485
18020,consistency_edges_89_100_100.pkl,pca_edges_1.pkl,0.1845,0.026700,0.046649

In [29]:
pca[pca.Recall == pca.Recall.max()]

,Reference Graph,Compared Graph,Precision,Recall,F1_score
4401,consistency_edges_1_1_1.pkl,pca_edges_100.pkl,0.000228,0.797203,0.000456

In [30]:
pca[pca.F1_score == pca.F1_score.max()]

,Reference Graph,Compared Graph,Precision,Recall,F1_score
4425,consistency_edges_1_1_100.pkl,pca_edges_1_whitened.pkl,0.1129,0.356151,0.17145

In [31]:
compared_graph_max, winners = find_best_compared_graphs(pca, 'F1_score')

In [32]:
compared_graph_max

{'consistency_edges_100_100_1.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_100_100.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_100_12.pkl': ['pca_edges_1_whitened.pkl'],
 'consistency_edges_100_100_23.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_100_34.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_100_45.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_100_56.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_100_67.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_100_78.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_100_89.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_12_1.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_12_100.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_12_12.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_12_23.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_12_34.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_12_45.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_12_56.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_12_67.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_12_78.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_12_89.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_1_1.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_1_100.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_1_12.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_1_23.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_1_34.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_1_45.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_1_56.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_1_67.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_1_78.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_1_89.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_23_1.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_23_100.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_23_12.pkl': ['pca_edges_1.pkl',
  'pca_edges_1_whitened.pkl'],
 'consistency_edges_100_23_23.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_23_34.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_23_45.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_23_56.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_23_67.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_23_78.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_23_89.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_34_1.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_34_100.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_34_12.pkl': ['pca_edges_1_whitened.pkl'],
 'consistency_edges_100_34_23.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_34_34.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_34_45.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_34_56.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_34_67.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_34_78.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_34_89.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_45_1.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_45_100.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_45_12.pkl': ['pca_edges_1_whitened.pkl'],
 'consistency_edges_100_45_23.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_45_34.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_45_45.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_45_56.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_45_67.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_45_78.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_45_89.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_56_1.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_56_100.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_56_12.pkl': ['pca_edges_1_whitened.pkl'],
 'consistency_edges_100_56_23.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_56_34.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_56_45.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_56_56.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_56_67.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_56_78.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_56_89.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_67_1.pkl': ['pca_edges_1_whitened.pkl'],
 'consistency_edges_100_67_100.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_67_12.pkl': ['pca_edges_1_whitened.pkl'],
 'consistency_edges_100_67_23.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_67_34.pkl': ['pca_edges_1_whitened.pkl'],
 'consistency_edges_100_67_45.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_67_56.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_67_67.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_67_78.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_67_89.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_78_1.pkl': ['pca_edges_1_whitened.pkl'],
 'consistency_edges_100_78_100.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_78_12.pkl': ['pca_edges_1_whitened.pkl'],
 'consistency_edges_100_78_23.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_78_34.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_78_45.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_78_56.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_78_67.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_78_78.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_78_89.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_89_1.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_89_100.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_89_12.pkl': ['pca_edges_1_whitened.pkl'],
 'consistency_edges_100_89_23.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_100_89_34.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_89_45.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_89_56.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_89_67.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_89_78.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_100_89_89.pkl': ['pca_edges_12.pkl'],
 'consistency_edges_12_100_1.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_100_100.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_100_12.pkl': ['pca_edges_1_whitened.pkl'],
 'consistency_edges_12_100_23.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_100_34.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_100_45.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_100_56.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_100_67.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_100_78.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_100_89.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_12_1.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_12_100.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_12_12.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_12_23.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_12_34.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_12_45.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_12_56.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_12_67.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_12_78.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_12_89.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_1_1.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_1_100.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_1_12.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_1_23.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_1_34.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_1_45.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_1_56.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_1_67.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_1_78.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_1_89.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_23_1.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_23_100.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_23_12.pkl': ['pca_edges_1_whitened.pkl'],
 'consistency_edges_12_23_23.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_23_34.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_23_45.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_23_56.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_23_67.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_23_78.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_23_89.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_34_1.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_34_100.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_34_12.pkl': ['pca_edges_1.pkl',
  'pca_edges_1_whitened.pkl'],
 'consistency_edges_12_34_23.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_34_34.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_34_45.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_34_56.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_34_67.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_34_78.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_34_89.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_45_1.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_45_100.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_45_12.pkl': ['pca_edges_1.pkl',
  'pca_edges_1_whitened.pkl'],
 'consistency_edges_12_45_23.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_45_34.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_45_45.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_45_56.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_45_67.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_45_78.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_45_89.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_56_1.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_56_100.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_56_12.pkl': ['pca_edges_1.pkl',
  'pca_edges_1_whitened.pkl'],
 'consistency_edges_12_56_23.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_56_34.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_56_45.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_56_56.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_56_67.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_56_78.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_56_89.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_67_1.pkl': ['pca_edges_1.pkl',
  'pca_edges_1_whitened.pkl'],
 'consistency_edges_12_67_100.pkl': ['pca_edges_1_whitened.pkl'],
 'consistency_edges_12_67_12.pkl': ['pca_edges_1_whitened.pkl'],
 'consistency_edges_12_67_23.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_67_34.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_67_45.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_67_56.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_67_67.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_67_78.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_67_89.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_78_1.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_78_100.pkl': ['pca_edges_1.pkl',
  'pca_edges_1_whitened.pkl'],
 'consistency_edges_12_78_12.pkl': ['pca_edges_1_whitened.pkl'],
 'consistency_edges_12_78_23.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_78_34.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_78_45.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_78_56.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_78_67.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_78_78.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_78_89.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_89_1.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_89_100.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_89_12.pkl': ['pca_edges_1.pkl',
  'pca_edges_1_whitened.pkl'],
 'consistency_edges_12_89_23.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_89_34.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_89_45.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_89_56.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_89_67.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_89_78.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_12_89_89.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_100_1.pkl': ['pca_edges_1_whitened.pkl'],
 'consistency_edges_1_100_100.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_100_12.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_100_23.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_100_34.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_100_45.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_100_56.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_100_67.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_100_78.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_100_89.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_12_1.pkl': ['pca_edges_1_whitened.pkl'],
 'consistency_edges_1_12_100.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_12_12.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_12_23.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_12_34.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_12_45.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_12_56.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_12_67.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_12_78.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_12_89.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_1_1.pkl': ['pca_edges_1_whitened.pkl'],
 'consistency_edges_1_1_100.pkl': ['pca_edges_1_whitened.pkl'],
 'consistency_edges_1_1_12.pkl': ['pca_edges_1_whitened.pkl'],
 'consistency_edges_1_1_23.pkl': ['pca_edges_1_whitened.pkl'],
 'consistency_edges_1_1_34.pkl': ['pca_edges_1_whitened.pkl'],
 'consistency_edges_1_1_45.pkl': ['pca_edges_1_whitened.pkl'],
 'consistency_edges_1_1_56.pkl': ['pca_edges_1_whitened.pkl'],
 'consistency_edges_1_1_67.pkl': ['pca_edges_1_whitened.pkl'],
 'consistency_edges_1_1_78.pkl': ['pca_edges_1_whitened.pkl'],
 'consistency_edges_1_1_89.pkl': ['pca_edges_1_whitened.pkl'],
 'consistency_edges_1_23_1.pkl': ['pca_edges_1_whitened.pkl'],
 'consistency_edges_1_23_100.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_23_12.pkl': ['pca_edges_1.pkl',
  'pca_edges_1_whitened.pkl'],
 'consistency_edges_1_23_23.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_23_34.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_23_45.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_23_56.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_23_67.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_23_78.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_23_89.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_34_1.pkl': ['pca_edges_1_whitened.pkl'],
 'consistency_edges_1_34_100.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_34_12.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_34_23.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_34_34.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_34_45.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_34_56.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_34_67.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_34_78.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_34_89.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_45_1.pkl': ['pca_edges_1_whitened.pkl'],
 'consistency_edges_1_45_100.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_45_12.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_45_23.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_45_34.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_45_45.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_45_56.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_45_67.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_45_78.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_45_89.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_56_1.pkl': ['pca_edges_1_whitened.pkl'],
 'consistency_edges_1_56_100.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_56_12.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_56_23.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_56_34.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_56_45.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_56_56.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_56_67.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_56_78.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_56_89.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_67_1.pkl': ['pca_edges_1_whitened.pkl'],
 'consistency_edges_1_67_100.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_67_12.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_67_23.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_67_34.pkl': ['pca_edges_1.pkl',
  'pca_edges_1_whitened.pkl'],
 'consistency_edges_1_67_45.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_67_56.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_67_67.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_67_78.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_67_89.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_78_1.pkl': ['pca_edges_1_whitened.pkl'],
 'consistency_edges_1_78_100.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_78_12.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_78_23.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_78_34.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_78_45.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_78_56.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_78_67.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_78_78.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_78_89.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_89_1.pkl': ['pca_edges_1_whitened.pkl'],
 'consistency_edges_1_89_100.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_89_12.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_89_23.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_89_34.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_89_45.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_89_56.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_89_67.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_89_78.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_1_89_89.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_100_1.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_100_100.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_100_12.pkl': ['pca_edges_1_whitened.pkl'],
 'consistency_edges_23_100_23.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_100_34.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_100_45.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_100_56.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_100_67.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_100_78.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_100_89.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_12_1.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_12_100.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_12_12.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_12_23.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_12_34.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_12_45.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_12_56.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_12_67.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_12_78.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_12_89.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_1_1.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_1_100.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_1_12.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_1_23.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_1_34.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_1_45.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_1_56.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_1_67.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_1_78.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_1_89.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_23_1.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_23_100.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_23_12.pkl': ['pca_edges_1.pkl',
  'pca_edges_1_whitened.pkl'],
 'consistency_edges_23_23_23.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_23_34.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_23_45.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_23_56.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_23_67.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_23_78.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_23_89.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_34_1.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_34_100.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_34_12.pkl': ['pca_edges_1_whitened.pkl'],
 'consistency_edges_23_34_23.pkl': ['pca_edges_1.pkl'],
 'consistency_edges_23_34_34.pkl': ['pca_edges_1.pkl'],

In [33]:
winners

{'pca_edges_1.pkl', 'pca_edges_12.pkl', 'pca_edges_1_whitened.pkl'}

### t-SNE

In [34]:
tsne

,Reference Graph,Compared Graph,Precision,Recall
0,consistency_edges_100_100_1.pkl,tsne_edges_100_10_pca.pkl,0.012664,0.414669
1,consistency_edges_100_100_1.pkl,tsne_edges_100_10_spectral.pkl,0.012568,0.411526
2,consistency_edges_100_100_1.pkl,tsne_edges_100_20_pca.pkl,0.013358,0.437394
3,consistency_edges_100_100_1.pkl,tsne_edges_100_20_spectral.pkl,0.013364,0.437590
4,consistency_edges_100_100_1.pkl,tsne_edges_100_30_pca.pkl,0.013166,0.431107
...,...,...,...,...
119995,consistency_edges_89_89_89.pkl,tsne_edges_89_40_spectral.pkl,0.028952,0.413556
119996,consistency_edges_89_89_89.pkl,tsne_edges_89_50_pca.pkl,0.028471,0.406686
119997,consistency_edges_89_89_89.pkl,tsne_edges_89_50_spectral.pkl,0.028919,0.413090
119998,consistency_edges_89_89_89.pkl,tsne_edges_89_5_pca.pkl,0.025336,0.361907
119999,consistency_edges_89_89_89.pkl,tsne_edges_89_5_spectral.pkl,0.024080,0.343964

In [35]:
tsne['F1_score'] = tsne.apply(lambda row: f1_score(row['Precision'], row['Recall']), axis=1)
tsne

,Reference Graph,Compared Graph,Precision,Recall,F1_score
0,consistency_edges_100_100_1.pkl,tsne_edges_100_10_pca.pkl,0.012664,0.414669,0.024577
1,consistency_edges_100_100_1.pkl,tsne_edges_100_10_spectral.pkl,0.012568,0.411526,0.024391
2,consistency_edges_100_100_1.pkl,tsne_edges_100_20_pca.pkl,0.013358,0.437394,0.025924
3,consistency_edges_100_100_1.pkl,tsne_edges_100_20_spectral.pkl,0.013364,0.437590,0.025936
4,consistency_edges_100_100_1.pkl,tsne_edges_100_30_pca.pkl,0.013166,0.431107,0.025552
...,...,...,...,...,...
119995,consistency_edges_89_89_89.pkl,tsne_edges_89_40_spectral.pkl,0.028952,0.413556,0.054115
119996,consistency_edges_89_89_89.pkl,tsne_edges_89_50_pca.pkl,0.028471,0.406686,0.053216
119997,consistency_edges_89_89_89.pkl,tsne_edges_89_50_spectral.pkl,0.028919,0.413090,0.054054
119998,consistency_edges_89_89_89.pkl,tsne_edges_89_5_pca.pkl,0.025336,0.361907,0.047357
119999,consistency_edges_89_89_89.pkl,tsne_edges_89_5_spectral.pkl,0.024080,0.343964,0.045009

In [36]:
tsne.describe()

           Precision         Recall       F1_score
count  120000.000000  120000.000000  120000.000000
mean        0.052727       0.478996       0.064231
std         0.071842       0.174944       0.045287
min         0.000271       0.046210       0.000542
25%         0.016200       0.396682       0.031471
50%         0.026106       0.488577       0.049550
75%         0.049853       0.583144       0.088899
max         0.344300       0.962514       0.286409

In [37]:
tsne[tsne.Precision == tsne.Precision.max()]

,Reference Graph,Compared Graph,Precision,Recall,F1_score
147,consistency_edges_100_100_100.pkl,tsne_edges_1_20_spectral.pkl,0.3443,0.047197,0.083015

In [38]:
tsne[tsne.Recall == tsne.Recall.max()]

,Reference Graph,Compared Graph,Precision,Recall,F1_score
26761,consistency_edges_1_1_23.pkl,tsne_edges_100_10_spectral.pkl,0.001669,0.962514,0.003332

In [39]:
tsne[tsne.F1_score == tsne.F1_score.max()]

,Reference Graph,Compared Graph,Precision,Recall,F1_score
26547,consistency_edges_1_1_100.pkl,tsne_edges_1_20_spectral.pkl,0.1886,0.594953,0.286409

In [40]:
compared_graph_max, winners = find_best_compared_graphs(tsne, 'F1_score')

In [41]:
compared_graph_max

{'consistency_edges_100_100_1.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_100_100.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_100_12.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_100_23.pkl': ['tsne_edges_12_30_spectral.pkl'],
 'consistency_edges_100_100_34.pkl': ['tsne_edges_12_30_spectral.pkl'],
 'consistency_edges_100_100_45.pkl': ['tsne_edges_12_30_spectral.pkl'],
 'consistency_edges_100_100_56.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_100_67.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_100_78.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_100_89.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_12_1.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_100_12_100.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_12_12.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_100_12_23.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_100_12_34.pkl': ['tsne_edges_1_50_pca.pkl'],
 'consistency_edges_100_12_45.pkl': ['tsne_edges_1_30_pca.pkl'],
 'consistency_edges_100_12_56.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_100_12_67.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_12_78.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_12_89.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_1_1.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_100_1_100.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_1_12.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_100_1_23.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_100_1_34.pkl': ['tsne_edges_1_50_pca.pkl'],
 'consistency_edges_100_1_45.pkl': ['tsne_edges_1_50_pca.pkl'],
 'consistency_edges_100_1_56.pkl': ['tsne_edges_1_20_spectral.pkl',
  'tsne_edges_1_50_pca.pkl'],
 'consistency_edges_100_1_67.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_100_1_78.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_1_89.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_23_1.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_100_23_100.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_23_12.pkl': ['tsne_edges_1_50_pca.pkl'],
 'consistency_edges_100_23_23.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_100_23_34.pkl': ['tsne_edges_1_50_pca.pkl'],
 'consistency_edges_100_23_45.pkl': ['tsne_edges_1_50_pca.pkl'],
 'consistency_edges_100_23_56.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_23_67.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_23_78.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_23_89.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_34_1.pkl': ['tsne_edges_1_50_pca.pkl'],
 'consistency_edges_100_34_100.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_34_12.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_100_34_23.pkl': ['tsne_edges_1_50_pca.pkl'],
 'consistency_edges_100_34_34.pkl': ['tsne_edges_1_50_pca.pkl'],
 'consistency_edges_100_34_45.pkl': ['tsne_edges_12_30_spectral.pkl'],
 'consistency_edges_100_34_56.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_34_67.pkl': ['tsne_edges_12_30_spectral.pkl'],
 'consistency_edges_100_34_78.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_34_89.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_45_1.pkl': ['tsne_edges_1_20_pca.pkl',
  'tsne_edges_1_50_pca.pkl'],
 'consistency_edges_100_45_100.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_45_12.pkl': ['tsne_edges_1_50_pca.pkl'],
 'consistency_edges_100_45_23.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_100_45_34.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_45_45.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_45_56.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_45_67.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_45_78.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_45_89.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_56_1.pkl': ['tsne_edges_1_5_spectral.pkl'],
 'consistency_edges_100_56_100.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_56_12.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_100_56_23.pkl': ['tsne_edges_12_30_spectral.pkl'],
 'consistency_edges_100_56_34.pkl': ['tsne_edges_12_30_spectral.pkl'],
 'consistency_edges_100_56_45.pkl': ['tsne_edges_12_30_spectral.pkl'],
 'consistency_edges_100_56_56.pkl': ['tsne_edges_12_20_spectral.pkl',
  'tsne_edges_12_30_spectral.pkl'],
 'consistency_edges_100_56_67.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_56_78.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_56_89.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_67_1.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_100_67_100.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_67_12.pkl': ['tsne_edges_12_30_spectral.pkl'],
 'consistency_edges_100_67_23.pkl': ['tsne_edges_12_30_spectral.pkl'],
 'consistency_edges_100_67_34.pkl': ['tsne_edges_12_30_spectral.pkl'],
 'consistency_edges_100_67_45.pkl': ['tsne_edges_12_30_spectral.pkl'],
 'consistency_edges_100_67_56.pkl': ['tsne_edges_12_30_spectral.pkl'],
 'consistency_edges_100_67_67.pkl': ['tsne_edges_12_30_spectral.pkl'],
 'consistency_edges_100_67_78.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_67_89.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_78_1.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_100_78_100.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_78_12.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_78_23.pkl': ['tsne_edges_12_30_spectral.pkl'],
 'consistency_edges_100_78_34.pkl': ['tsne_edges_12_30_spectral.pkl'],
 'consistency_edges_100_78_45.pkl': ['tsne_edges_12_30_spectral.pkl'],
 'consistency_edges_100_78_56.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_78_67.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_78_78.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_78_89.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_89_1.pkl': ['tsne_edges_12_30_spectral.pkl'],
 'consistency_edges_100_89_100.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_89_12.pkl': ['tsne_edges_12_30_spectral.pkl'],
 'consistency_edges_100_89_23.pkl': ['tsne_edges_12_30_spectral.pkl'],
 'consistency_edges_100_89_34.pkl': ['tsne_edges_12_30_spectral.pkl'],
 'consistency_edges_100_89_45.pkl': ['tsne_edges_12_30_spectral.pkl'],
 'consistency_edges_100_89_56.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_89_67.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_89_78.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_89_89.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_12_100_1.pkl': ['tsne_edges_1_20_pca.pkl'],
 'consistency_edges_12_100_100.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_12_100_12.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_100_23.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_100_34.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_12_100_45.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_100_56.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_100_67.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_12_100_78.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_12_100_89.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_12_12_1.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_12_100.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_12_12.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_12_12_23.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_12_12_34.pkl': ['tsne_edges_1_30_spectral.pkl',
  'tsne_edges_1_50_pca.pkl'],
 'consistency_edges_12_12_45.pkl': ['tsne_edges_1_30_pca.pkl'],
 'consistency_edges_12_12_56.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_12_67.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_12_78.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_12_89.pkl': ['tsne_edges_1_30_pca.pkl'],
 'consistency_edges_12_1_1.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_12_1_100.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_1_12.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_12_1_23.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_12_1_34.pkl': ['tsne_edges_1_30_spectral.pkl',
  'tsne_edges_1_50_pca.pkl'],
 'consistency_edges_12_1_45.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_1_56.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_1_67.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_1_78.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_1_89.pkl': ['tsne_edges_1_40_pca.pkl'],
 'consistency_edges_12_23_1.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_23_100.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_23_12.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_12_23_23.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_23_34.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_23_45.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_23_56.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_23_67.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_23_78.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_23_89.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_34_1.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_34_100.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_34_12.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_12_34_23.pkl': ['tsne_edges_1_50_pca.pkl'],
 'consistency_edges_12_34_34.pkl': ['tsne_edges_1_50_pca.pkl'],
 'consistency_edges_12_34_45.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_34_56.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_34_67.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_12_34_78.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_34_89.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_12_45_1.pkl': ['tsne_edges_1_50_pca.pkl'],
 'consistency_edges_12_45_100.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_12_45_12.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_12_45_23.pkl': ['tsne_edges_1_30_spectral.pkl',
  'tsne_edges_1_50_pca.pkl'],
 'consistency_edges_12_45_34.pkl': ['tsne_edges_1_30_spectral.pkl',
  'tsne_edges_1_50_pca.pkl'],
 'consistency_edges_12_45_45.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_45_56.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_45_67.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_12_45_78.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_45_89.pkl': ['tsne_edges_1_20_spectral.pkl',
  'tsne_edges_1_30_pca.pkl'],
 'consistency_edges_12_56_1.pkl': ['tsne_edges_1_5_spectral.pkl'],
 'consistency_edges_12_56_100.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_12_56_12.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_12_56_23.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_56_34.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_56_45.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_56_56.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_56_67.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_12_56_78.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_56_89.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_12_67_1.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_12_67_100.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_12_67_12.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_12_67_23.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_67_34.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_67_45.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_67_56.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_67_67.pkl': ['tsne_edges_1_20_pca.pkl',
  'tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_12_67_78.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_67_89.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_12_78_1.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_12_78_100.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_12_78_12.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_12_78_23.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_78_34.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_78_45.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_78_56.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_78_67.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_12_78_78.pkl': ['tsne_edges_1_30_pca.pkl'],
 'consistency_edges_12_78_89.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_12_89_1.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_12_89_100.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_12_89_12.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_12_89_23.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_89_34.pkl': ['tsne_edges_1_20_spectral.pkl',
  'tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_89_45.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_89_56.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_89_67.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_12_89_78.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_89_89.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_1_100_1.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_100_100.pkl': ['tsne_edges_1_20_pca.pkl'],
 'consistency_edges_1_100_12.pkl': ['tsne_edges_1_20_pca.pkl'],
 'consistency_edges_1_100_23.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_100_34.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_100_45.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_100_56.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_100_67.pkl': ['tsne_edges_1_20_pca.pkl',
  'tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_100_78.pkl': ['tsne_edges_1_20_pca.pkl'],
 'consistency_edges_1_100_89.pkl': ['tsne_edges_1_20_pca.pkl',
  'tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_12_1.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_1_12_100.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_12_12.pkl': ['tsne_edges_1_20_pca.pkl'],
 'consistency_edges_1_12_23.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_12_34.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_12_45.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_12_56.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_12_67.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_12_78.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_12_89.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_1_1.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_1_1_100.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_1_12.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_1_23.pkl': ['tsne_edges_1_10_spectral.pkl',
  'tsne_edges_1_20_spectral.pkl',
  'tsne_edges_1_50_pca.pkl'],
 'consistency_edges_1_1_34.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_1_45.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_1_56.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_1_67.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_1_78.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_1_89.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_23_1.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_1_23_100.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_23_12.pkl': ['tsne_edges_1_20_pca.pkl'],
 'consistency_edges_1_23_23.pkl': ['tsne_edges_1_20_spectral.pkl',
  'tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_1_23_34.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_23_45.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_23_56.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_23_67.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_23_78.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_23_89.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_34_1.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_1_34_100.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_34_12.pkl': ['tsne_edges_1_20_pca.pkl'],
 'consistency_edges_1_34_23.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_34_34.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_34_45.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_34_56.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_34_67.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_34_78.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_34_89.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_45_1.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_45_100.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_45_12.pkl': ['tsne_edges_1_20_pca.pkl'],
 'consistency_edges_1_45_23.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_45_34.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_45_45.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_45_56.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_45_67.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_45_78.pkl': ['tsne_edges_1_20_pca.pkl',
  'tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_45_89.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_56_1.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_56_100.pkl': ['tsne_edges_1_20_pca.pkl'],
 'consistency_edges_1_56_12.pkl': ['tsne_edges_1_20_pca.pkl'],
 'consistency_edges_1_56_23.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_56_34.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_56_45.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_56_56.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_56_67.pkl': ['tsne_edges_1_20_pca.pkl'],
 'consistency_edges_1_56_78.pkl': ['tsne_edges_1_20_pca.pkl'],
 'consistency_edges_1_56_89.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_67_1.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_67_100.pkl': ['tsne_edges_1_20_pca.pkl'],
 'consistency_edges_1_67_12.pkl': ['tsne_edges_1_20_pca.pkl'],
 'consistency_edges_1_67_23.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_67_34.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_67_45.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_67_56.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_67_67.pkl': ['tsne_edges_1_20_pca.pkl'],
 'consistency_edges_1_67_78.pkl': ['tsne_edges_1_20_pca.pkl'],
 'consistency_edges_1_67_89.pkl': ['tsne_edges_1_20_pca.pkl'],
 'consistency_edges_1_78_1.pkl': ['tsne_edges_1_20_spectral.pkl'],
 'consistency_edges_1_78_100.pkl': ['tsne_edges_1_20_pca.pkl'],
 'consistency_edges_1_78_12.pkl': ['tsne_edges_1_20_pca.pkl'],
 'consistency_edges_1_78_23.pkl': ['tsne_edges_1_10_spectral.pkl',

In [42]:
winners

{'tsne_edges_12_20_spectral.pkl',
 'tsne_edges_12_30_spectral.pkl',
 'tsne_edges_12_40_spectral.pkl',
 'tsne_edges_1_10_pca.pkl',
 'tsne_edges_1_10_spectral.pkl',
 'tsne_edges_1_20_pca.pkl',
 'tsne_edges_1_20_spectral.pkl',
 'tsne_edges_1_30_pca.pkl',
 'tsne_edges_1_30_spectral.pkl',
 'tsne_edges_1_40_pca.pkl',
 'tsne_edges_1_50_pca.pkl',
 'tsne_edges_1_5_spectral.pkl'}

### t-SNE + PCA

In [43]:
tsne_pca

,Reference Graph,Compared Graph,Precision,Recall
0,consistency_edges_100_100_1.pkl,tsne_edges_100_10_pca.pkl,0.012273,0.401866
1,consistency_edges_100_100_1.pkl,tsne_edges_100_10_spectral.pkl,0.012341,0.404093
2,consistency_edges_100_100_1.pkl,tsne_edges_100_20_pca.pkl,0.012954,0.424165
3,consistency_edges_100_100_1.pkl,tsne_edges_100_20_spectral.pkl,0.012680,0.415193
4,consistency_edges_100_100_1.pkl,tsne_edges_100_30_pca.pkl,0.012981,0.425049
...,...,...,...,...
99995,consistency_edges_89_89_89.pkl,tsne_edges_89_30_spectral.pkl,0.027428,0.391792
99996,consistency_edges_89_89_89.pkl,tsne_edges_89_40_pca.pkl,0.027073,0.386720
99997,consistency_edges_89_89_89.pkl,tsne_edges_89_40_spectral.pkl,0.027148,0.387796
99998,consistency_edges_89_89_89.pkl,tsne_edges_89_5_pca.pkl,0.024443,0.349148
99999,consistency_edges_89_89_89.pkl,tsne_edges_89_5_spectral.pkl,0.023706,0.338619

In [44]:
tsne_pca['F1_score'] = tsne_pca.apply(lambda row: f1_score(row['Precision'], row['Recall']), axis=1)
tsne_pca

,Reference Graph,Compared Graph,Precision,Recall,F1_score
0,consistency_edges_100_100_1.pkl,tsne_edges_100_10_pca.pkl,0.012273,0.401866,0.023819
1,consistency_edges_100_100_1.pkl,tsne_edges_100_10_spectral.pkl,0.012341,0.404093,0.023951
2,consistency_edges_100_100_1.pkl,tsne_edges_100_20_pca.pkl,0.012954,0.424165,0.025140
3,consistency_edges_100_100_1.pkl,tsne_edges_100_20_spectral.pkl,0.012680,0.415193,0.024608
4,consistency_edges_100_100_1.pkl,tsne_edges_100_30_pca.pkl,0.012981,0.425049,0.025193
...,...,...,...,...,...
99995,consistency_edges_89_89_89.pkl,tsne_edges_89_30_spectral.pkl,0.027428,0.391792,0.051267
99996,consistency_edges_89_89_89.pkl,tsne_edges_89_40_pca.pkl,0.027073,0.386720,0.050603
99997,consistency_edges_89_89_89.pkl,tsne_edges_89_40_spectral.pkl,0.027148,0.387796,0.050744
99998,consistency_edges_89_89_89.pkl,tsne_edges_89_5_pca.pkl,0.024443,0.349148,0.045687
99999,consistency_edges_89_89_89.pkl,tsne_edges_89_5_spectral.pkl,0.023706,0.338619,0.044309

In [45]:
tsne_pca.describe()

           Precision         Recall       F1_score
count  100000.000000  100000.000000  100000.000000
mean        0.050325       0.460910       0.061554
std         0.068014       0.169532       0.043168
min         0.000263       0.043866       0.000526
25%         0.015588       0.381912       0.030288
50%         0.025020       0.469265       0.047478
75%         0.048124       0.560743       0.085757
max         0.325700       0.949229       0.275019

In [46]:
tsne_pca[tsne_pca.Precision == tsne_pca.Precision.max()]

,Reference Graph,Compared Graph,Precision,Recall,F1_score
125,consistency_edges_100_100_100.pkl,tsne_edges_1_30_spectral.pkl,0.3257,0.044648,0.07853

In [47]:
tsne_pca[tsne_pca.Recall == tsne_pca.Recall.max()]

,Reference Graph,Compared Graph,Precision,Recall,F1_score
22209,consistency_edges_1_1_12.pkl,tsne_edges_100_5_spectral.pkl,0.001047,0.949229,0.002092

In [48]:
tsne_pca[tsne_pca.F1_score == tsne_pca.F1_score.max()]

,Reference Graph,Compared Graph,Precision,Recall,F1_score
22128,consistency_edges_1_1_100.pkl,tsne_edges_1_5_pca.pkl,0.1811,0.571293,0.275019

In [49]:
compared_graph_max, winners = find_best_compared_graphs(tsne_pca, 'F1_score')

In [50]:
compared_graph_max

{'consistency_edges_100_100_1.pkl': ['tsne_edges_12_30_pca.pkl'],
 'consistency_edges_100_100_100.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_100_12.pkl': ['tsne_edges_12_30_pca.pkl'],
 'consistency_edges_100_100_23.pkl': ['tsne_edges_12_20_pca.pkl'],
 'consistency_edges_100_100_34.pkl': ['tsne_edges_12_20_pca.pkl'],
 'consistency_edges_100_100_45.pkl': ['tsne_edges_12_20_pca.pkl'],
 'consistency_edges_100_100_56.pkl': ['tsne_edges_12_20_pca.pkl'],
 'consistency_edges_100_100_67.pkl': ['tsne_edges_12_20_pca.pkl'],
 'consistency_edges_100_100_78.pkl': ['tsne_edges_12_20_pca.pkl'],
 'consistency_edges_100_100_89.pkl': ['tsne_edges_12_20_pca.pkl'],
 'consistency_edges_100_12_1.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_100_12_100.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_12_12.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_100_12_23.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_100_12_34.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_100_12_45.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_100_12_56.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_12_67.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_12_78.pkl': ['tsne_edges_12_20_pca.pkl'],
 'consistency_edges_100_12_89.pkl': ['tsne_edges_12_20_pca.pkl'],
 'consistency_edges_100_1_1.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_100_1_100.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_1_12.pkl': ['tsne_edges_1_5_pca.pkl'],
 'consistency_edges_100_1_23.pkl': ['tsne_edges_1_5_pca.pkl'],
 'consistency_edges_100_1_34.pkl': ['tsne_edges_1_5_pca.pkl'],
 'consistency_edges_100_1_45.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_100_1_56.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_100_1_67.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_100_1_78.pkl': ['tsne_edges_12_20_pca.pkl'],
 'consistency_edges_100_1_89.pkl': ['tsne_edges_12_20_pca.pkl'],
 'consistency_edges_100_23_1.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_100_23_100.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_23_12.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_100_23_23.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_100_23_34.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_100_23_45.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_23_56.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_23_67.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_23_78.pkl': ['tsne_edges_12_20_pca.pkl'],
 'consistency_edges_100_23_89.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_34_1.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_100_34_100.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_34_12.pkl': ['tsne_edges_1_30_pca.pkl'],
 'consistency_edges_100_34_23.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_100_34_34.pkl': ['tsne_edges_12_20_pca.pkl'],
 'consistency_edges_100_34_45.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_34_56.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_34_67.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_34_78.pkl': ['tsne_edges_12_20_pca.pkl'],
 'consistency_edges_100_34_89.pkl': ['tsne_edges_12_20_pca.pkl'],
 'consistency_edges_100_45_1.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_100_45_100.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_45_12.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_100_45_23.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_100_45_34.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_45_45.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_45_56.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_45_67.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_45_78.pkl': ['tsne_edges_12_20_pca.pkl'],
 'consistency_edges_100_45_89.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_56_1.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_100_56_100.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_56_12.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_100_56_23.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_56_34.pkl': ['tsne_edges_12_20_pca.pkl'],
 'consistency_edges_100_56_45.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_56_56.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_56_67.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_56_78.pkl': ['tsne_edges_12_20_pca.pkl'],
 'consistency_edges_100_56_89.pkl': ['tsne_edges_12_20_pca.pkl'],
 'consistency_edges_100_67_1.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_100_67_100.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_67_12.pkl': ['tsne_edges_12_20_pca.pkl'],
 'consistency_edges_100_67_23.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_67_34.pkl': ['tsne_edges_12_20_pca.pkl'],
 'consistency_edges_100_67_45.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_67_56.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_67_67.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_67_78.pkl': ['tsne_edges_12_20_pca.pkl'],
 'consistency_edges_100_67_89.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_78_1.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_100_78_100.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_78_12.pkl': ['tsne_edges_12_20_pca.pkl'],
 'consistency_edges_100_78_23.pkl': ['tsne_edges_12_20_pca.pkl'],
 'consistency_edges_100_78_34.pkl': ['tsne_edges_12_20_pca.pkl'],
 'consistency_edges_100_78_45.pkl': ['tsne_edges_12_20_pca.pkl'],
 'consistency_edges_100_78_56.pkl': ['tsne_edges_12_20_pca.pkl'],
 'consistency_edges_100_78_67.pkl': ['tsne_edges_12_20_pca.pkl'],
 'consistency_edges_100_78_78.pkl': ['tsne_edges_12_20_pca.pkl'],
 'consistency_edges_100_78_89.pkl': ['tsne_edges_12_20_pca.pkl'],
 'consistency_edges_100_89_1.pkl': ['tsne_edges_12_30_pca.pkl'],
 'consistency_edges_100_89_100.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_89_12.pkl': ['tsne_edges_12_20_pca.pkl',
  'tsne_edges_12_30_pca.pkl'],
 'consistency_edges_100_89_23.pkl': ['tsne_edges_12_20_pca.pkl'],
 'consistency_edges_100_89_34.pkl': ['tsne_edges_12_20_pca.pkl'],
 'consistency_edges_100_89_45.pkl': ['tsne_edges_12_20_pca.pkl'],
 'consistency_edges_100_89_56.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_100_89_67.pkl': ['tsne_edges_12_20_pca.pkl'],
 'consistency_edges_100_89_78.pkl': ['tsne_edges_12_20_pca.pkl'],
 'consistency_edges_100_89_89.pkl': ['tsne_edges_12_20_pca.pkl'],
 'consistency_edges_12_100_1.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_100_100.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_12_100_12.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_12_100_23.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_100_34.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_100_45.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_100_56.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_100_67.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_100_78.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_100_89.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_12_12_1.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_12_100.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_12_12.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_12_23.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_12_34.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_12_45.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_12_56.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_12_67.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_12_78.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_12_89.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_1_1.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_1_100.pkl': ['tsne_edges_1_5_pca.pkl'],
 'consistency_edges_12_1_12.pkl': ['tsne_edges_1_5_pca.pkl'],
 'consistency_edges_12_1_23.pkl': ['tsne_edges_1_5_pca.pkl'],
 'consistency_edges_12_1_34.pkl': ['tsne_edges_1_5_pca.pkl'],
 'consistency_edges_12_1_45.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_1_56.pkl': ['tsne_edges_1_5_spectral.pkl'],
 'consistency_edges_12_1_67.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_12_1_78.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_12_1_89.pkl': ['tsne_edges_1_5_spectral.pkl'],
 'consistency_edges_12_23_1.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_23_100.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_23_12.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_23_23.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_23_34.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_23_45.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_23_56.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_23_67.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_23_78.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_23_89.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_34_1.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_34_100.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_34_12.pkl': ['tsne_edges_1_10_spectral.pkl',
  'tsne_edges_1_30_pca.pkl'],
 'consistency_edges_12_34_23.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_34_34.pkl': ['tsne_edges_1_10_spectral.pkl',
  'tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_34_45.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_12_34_56.pkl': ['tsne_edges_1_30_pca.pkl',
  'tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_34_67.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_34_78.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_34_89.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_45_1.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_45_100.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_45_12.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_45_23.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_45_34.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_45_45.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_45_56.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_45_67.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_45_78.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_45_89.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_56_1.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_56_100.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_56_12.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_56_23.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_56_34.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_56_45.pkl': ['tsne_edges_1_10_pca.pkl',
  'tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_56_56.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_56_67.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_56_78.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_56_89.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_67_1.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_67_100.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_67_12.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_67_23.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_67_34.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_67_45.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_67_56.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_67_67.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_67_78.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_67_89.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_78_1.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_78_100.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_12_78_12.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_12_78_23.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_78_34.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_12_78_45.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_12_78_56.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_78_67.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_78_78.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_78_89.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_89_1.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_89_100.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_12_89_12.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_12_89_23.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_89_34.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_89_45.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_89_56.pkl': ['tsne_edges_1_30_spectral.pkl'],
 'consistency_edges_12_89_67.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_89_78.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_12_89_89.pkl': ['tsne_edges_12_20_spectral.pkl'],
 'consistency_edges_1_100_1.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_100_100.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_100_12.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_100_23.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_100_34.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_100_45.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_100_56.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_100_67.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_100_78.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_100_89.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_12_1.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_1_12_100.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_12_12.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_12_23.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_12_34.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_12_45.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_12_56.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_12_67.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_12_78.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_12_89.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_1_1.pkl': ['tsne_edges_1_5_pca.pkl'],
 'consistency_edges_1_1_100.pkl': ['tsne_edges_1_5_pca.pkl'],
 'consistency_edges_1_1_12.pkl': ['tsne_edges_1_5_pca.pkl'],
 'consistency_edges_1_1_23.pkl': ['tsne_edges_1_5_pca.pkl'],
 'consistency_edges_1_1_34.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_1_45.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_1_56.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_1_67.pkl': ['tsne_edges_1_5_pca.pkl'],
 'consistency_edges_1_1_78.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_1_89.pkl': ['tsne_edges_1_5_pca.pkl'],
 'consistency_edges_1_23_1.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_23_100.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_23_12.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_23_23.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_23_34.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_23_45.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_23_56.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_23_67.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_23_78.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_23_89.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_34_1.pkl': ['tsne_edges_1_20_pca.pkl'],
 'consistency_edges_1_34_100.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_34_12.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_34_23.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_34_34.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_34_45.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_34_56.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_34_67.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_34_78.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_34_89.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_45_1.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_1_45_100.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_45_12.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_45_23.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_45_34.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_45_45.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_45_56.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_45_67.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_45_78.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_45_89.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_56_1.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_1_56_100.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_56_12.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_56_23.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_56_34.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_56_45.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_56_56.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_56_67.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_56_78.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_56_89.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_67_1.pkl': ['tsne_edges_1_10_pca.pkl'],
 'consistency_edges_1_67_100.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_67_12.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_67_23.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_67_34.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_67_45.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_67_56.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_67_67.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_67_78.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_67_89.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_78_1.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_78_100.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_78_12.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_78_23.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_78_34.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_78_45.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_78_56.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_78_67.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_78_78.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_78_89.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_89_1.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_89_100.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_89_12.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_89_23.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_89_34.pkl': ['tsne_edges_1_10_spectral.pkl'],
 'consistency_edges_1_89_45.pkl': ['tsne_edges_1_10_spectral.pkl'],

In [51]:
winners

{'tsne_edges_12_20_pca.pkl',
 'tsne_edges_12_20_spectral.pkl',
 'tsne_edges_12_30_pca.pkl',
 'tsne_edges_1_10_pca.pkl',
 'tsne_edges_1_10_spectral.pkl',
 'tsne_edges_1_20_pca.pkl',
 'tsne_edges_1_30_pca.pkl',
 'tsne_edges_1_30_spectral.pkl',
 'tsne_edges_1_5_pca.pkl',
 'tsne_edges_1_5_spectral.pkl'}

### UMAP

In [52]:
umap

,Reference Graph,Compared Graph,Precision,Recall
0,consistency_edges_100_100_1.pkl,umap_edges_100_101_0.0_pca.pkl,0.009122,0.171611
1,consistency_edges_100_100_1.pkl,umap_edges_100_101_0.0_spectral.pkl,0.009187,0.172823
2,consistency_edges_100_100_1.pkl,umap_edges_100_101_0.25_pca.pkl,0.008763,0.160183
3,consistency_edges_100_100_1.pkl,umap_edges_100_101_0.25_spectral.pkl,0.008653,0.159136
4,consistency_edges_100_100_1.pkl,umap_edges_100_101_0.5_pca.pkl,0.008219,0.149050
...,...,...,...,...
999995,consistency_edges_89_89_89.pkl,umap_edges_89_90_0.5_spectral.pkl,0.018342,0.145171
999996,consistency_edges_89_89_89.pkl,umap_edges_89_90_0.75_pca.pkl,0.017301,0.136231
999997,consistency_edges_89_89_89.pkl,umap_edges_89_90_0.75_spectral.pkl,0.016884,0.132973
999998,consistency_edges_89_89_89.pkl,umap_edges_89_90_0.99_pca.pkl,0.016659,0.130950
999999,consistency_edges_89_89_89.pkl,umap_edges_89_90_0.99_spectral.pkl,0.016334,0.128415

In [53]:
umap['F1_score'] = umap.apply(lambda row: f1_score(row['Precision'], row['Recall']), axis=1)
umap

,Reference Graph,Compared Graph,Precision,Recall,F1_score
0,consistency_edges_100_100_1.pkl,umap_edges_100_101_0.0_pca.pkl,0.009122,0.171611,0.017323
1,consistency_edges_100_100_1.pkl,umap_edges_100_101_0.0_spectral.pkl,0.009187,0.172823,0.017447
2,consistency_edges_100_100_1.pkl,umap_edges_100_101_0.25_pca.pkl,0.008763,0.160183,0.016616
3,consistency_edges_100_100_1.pkl,umap_edges_100_101_0.25_spectral.pkl,0.008653,0.159136,0.016414
4,consistency_edges_100_100_1.pkl,umap_edges_100_101_0.5_pca.pkl,0.008219,0.149050,0.015579
...,...,...,...,...,...
999995,consistency_edges_89_89_89.pkl,umap_edges_89_90_0.5_spectral.pkl,0.018342,0.145171,0.032569
999996,consistency_edges_89_89_89.pkl,umap_edges_89_90_0.75_pca.pkl,0.017301,0.136231,0.030703
999997,consistency_edges_89_89_89.pkl,umap_edges_89_90_0.75_spectral.pkl,0.016884,0.132973,0.029964
999998,consistency_edges_89_89_89.pkl,umap_edges_89_90_0.99_pca.pkl,0.016659,0.130950,0.029558
999999,consistency_edges_89_89_89.pkl,umap_edges_89_90_0.99_spectral.pkl,0.016334,0.128415,0.028982

In [54]:
umap.describe()

            Precision          Recall        F1_score
count  1000000.000000  1000000.000000  1000000.000000
mean         0.022542        0.154957        0.029243
std          0.023901        0.070399        0.017358
min          0.000133        0.003925        0.000265
25%          0.009242        0.112415        0.016463
50%          0.015726        0.159200        0.026380
75%          0.026606        0.200938        0.038749
max          0.238704        0.425794        0.140774

In [55]:
umap[umap.Precision == umap.Precision.max()]

,Reference Graph,Compared Graph,Precision,Recall,F1_score
1231,consistency_edges_100_100_100.pkl,umap_edges_1_2_0.0_spectral.pkl,0.238704,0.022015,0.040313

In [56]:
umap[umap.Recall == umap.Recall.max()]

,Reference Graph,Compared Graph,Precision,Recall,F1_score
121010,consistency_edges_12_1_100.pkl,umap_edges_100_13_0.0_pca.pkl,0.009695,0.425794,0.018959

In [57]:
umap[umap.F1_score == umap.F1_score.max()]

,Reference Graph,Compared Graph,Precision,Recall,F1_score
221232,consistency_edges_1_1_100.pkl,umap_edges_1_2_0.25_pca.pkl,0.103669,0.219243,0.140774

In [58]:
compared_graph_max, winners = find_best_compared_graphs(umap, 'F1_score')

In [59]:
compared_graph_max

{'consistency_edges_100_100_1.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_100_100.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_100_12.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_100_23.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_100_34.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_100_45.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_100_56.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_100_67.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_100_78.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_100_89.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_12_1.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_100_12_100.pkl': ['umap_edges_12_13_0.0_pca.pkl'],
 'consistency_edges_100_12_12.pkl': ['umap_edges_1_2_0.0_pca.pkl'],
 'consistency_edges_100_12_23.pkl': ['umap_edges_1_2_0.25_spectral.pkl'],
 'consistency_edges_100_12_34.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_100_12_45.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_12_56.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_12_67.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_12_78.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_12_89.pkl': ['umap_edges_12_13_0.0_pca.pkl'],
 'consistency_edges_100_1_1.pkl': ['umap_edges_1_2_0.25_spectral.pkl'],
 'consistency_edges_100_1_100.pkl': ['umap_edges_12_13_0.0_pca.pkl'],
 'consistency_edges_100_1_12.pkl': ['umap_edges_1_2_0.25_spectral.pkl'],
 'consistency_edges_100_1_23.pkl': ['umap_edges_1_2_0.25_spectral.pkl'],
 'consistency_edges_100_1_34.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_100_1_45.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_100_1_56.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_1_67.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_1_78.pkl': ['umap_edges_12_13_0.0_pca.pkl'],
 'consistency_edges_100_1_89.pkl': ['umap_edges_12_13_0.0_pca.pkl'],
 'consistency_edges_100_23_1.pkl': ['umap_edges_1_2_0.0_pca.pkl'],
 'consistency_edges_100_23_100.pkl': ['umap_edges_12_13_0.0_pca.pkl'],
 'consistency_edges_100_23_12.pkl': ['umap_edges_1_2_0.0_pca.pkl'],
 'consistency_edges_100_23_23.pkl': ['umap_edges_1_2_0.0_pca.pkl'],
 'consistency_edges_100_23_34.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_23_45.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_23_56.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_23_67.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_23_78.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_23_89.pkl': ['umap_edges_12_13_0.0_pca.pkl'],
 'consistency_edges_100_34_1.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_100_34_100.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_34_12.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_34_23.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_34_34.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_34_45.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_34_56.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_34_67.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_34_78.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_34_89.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_45_1.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_45_100.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_45_12.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_45_23.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_45_34.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_45_45.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_45_56.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_45_67.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_45_78.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_45_89.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_56_1.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_56_100.pkl': ['umap_edges_12_13_0.0_pca.pkl'],
 'consistency_edges_100_56_12.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_56_23.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_56_34.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_56_45.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_56_56.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_56_67.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_56_78.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_56_89.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_67_1.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_67_100.pkl': ['umap_edges_12_13_0.0_pca.pkl'],
 'consistency_edges_100_67_12.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_67_23.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_67_34.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_67_45.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_67_56.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_67_67.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_67_78.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_67_89.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_78_1.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_78_100.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_78_12.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_78_23.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_78_34.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_78_45.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_78_56.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_78_67.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_78_78.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_78_89.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_89_1.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_89_100.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_89_12.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_89_23.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_89_34.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_89_45.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_89_56.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_89_67.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_89_78.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_100_89_89.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_12_100_1.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_12_100_100.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_12_100_12.pkl': ['umap_edges_1_2_0.0_pca.pkl'],
 'consistency_edges_12_100_23.pkl': ['umap_edges_1_2_0.0_pca.pkl'],
 'consistency_edges_12_100_34.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_12_100_45.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_12_100_56.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_12_100_67.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_12_100_78.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_12_100_89.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_12_12_1.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_12_12_100.pkl': ['umap_edges_1_2_0.0_pca.pkl'],
 'consistency_edges_12_12_12.pkl': ['umap_edges_1_2_0.0_pca.pkl'],
 'consistency_edges_12_12_23.pkl': ['umap_edges_1_2_0.0_pca.pkl'],
 'consistency_edges_12_12_34.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_12_12_45.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_12_12_56.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_12_12_67.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_12_12_78.pkl': ['umap_edges_1_2_0.25_spectral.pkl'],
 'consistency_edges_12_12_89.pkl': ['umap_edges_1_2_0.25_spectral.pkl'],
 'consistency_edges_12_1_1.pkl': ['umap_edges_1_2_0.25_spectral.pkl'],
 'consistency_edges_12_1_100.pkl': ['umap_edges_1_2_0.25_spectral.pkl'],
 'consistency_edges_12_1_12.pkl': ['umap_edges_1_2_0.25_spectral.pkl'],
 'consistency_edges_12_1_23.pkl': ['umap_edges_1_2_0.25_spectral.pkl'],
 'consistency_edges_12_1_34.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_12_1_45.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_12_1_56.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_12_1_67.pkl': ['umap_edges_1_2_0.25_spectral.pkl'],
 'consistency_edges_12_1_78.pkl': ['umap_edges_1_2_0.25_spectral.pkl'],
 'consistency_edges_12_1_89.pkl': ['umap_edges_1_2_0.25_spectral.pkl'],
 'consistency_edges_12_23_1.pkl': ['umap_edges_1_2_0.0_pca.pkl'],
 'consistency_edges_12_23_100.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_12_23_12.pkl': ['umap_edges_1_2_0.0_pca.pkl'],
 'consistency_edges_12_23_23.pkl': ['umap_edges_1_2_0.0_pca.pkl'],
 'consistency_edges_12_23_34.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_12_23_45.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_12_23_56.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_12_23_67.pkl': ['umap_edges_1_2_0.0_pca.pkl'],
 'consistency_edges_12_23_78.pkl': ['umap_edges_1_2_0.25_spectral.pkl'],
 'consistency_edges_12_23_89.pkl': ['umap_edges_1_2_0.25_spectral.pkl'],
 'consistency_edges_12_34_1.pkl': ['umap_edges_1_2_0.0_pca.pkl'],
 'consistency_edges_12_34_100.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_12_34_12.pkl': ['umap_edges_1_2_0.0_pca.pkl'],
 'consistency_edges_12_34_23.pkl': ['umap_edges_1_2_0.0_pca.pkl'],
 'consistency_edges_12_34_34.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_12_34_45.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_12_34_56.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_12_34_67.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_12_34_78.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_12_34_89.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_12_45_1.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_12_45_100.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_12_45_12.pkl': ['umap_edges_1_2_0.0_pca.pkl'],
 'consistency_edges_12_45_23.pkl': ['umap_edges_1_2_0.0_pca.pkl'],
 'consistency_edges_12_45_34.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_12_45_45.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_12_45_56.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_12_45_67.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_12_45_78.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_12_45_89.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_12_56_1.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_12_56_100.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_12_56_12.pkl': ['umap_edges_1_2_0.0_pca.pkl'],
 'consistency_edges_12_56_23.pkl': ['umap_edges_1_2_0.0_pca.pkl'],
 'consistency_edges_12_56_34.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_12_56_45.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_12_56_56.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_12_56_67.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_12_56_78.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_12_56_89.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_12_67_1.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_12_67_100.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_12_67_12.pkl': ['umap_edges_1_2_0.0_pca.pkl'],
 'consistency_edges_12_67_23.pkl': ['umap_edges_1_2_0.0_pca.pkl'],
 'consistency_edges_12_67_34.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_12_67_45.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_12_67_56.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_12_67_67.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_12_67_78.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_12_67_89.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_12_78_1.pkl': ['umap_edges_1_2_0.0_pca.pkl'],
 'consistency_edges_12_78_100.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_12_78_12.pkl': ['umap_edges_1_2_0.0_pca.pkl'],
 'consistency_edges_12_78_23.pkl': ['umap_edges_1_2_0.0_pca.pkl'],
 'consistency_edges_12_78_34.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_12_78_45.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_12_78_56.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_12_78_67.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_12_78_78.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_12_78_89.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_12_89_1.pkl': ['umap_edges_1_2_0.0_pca.pkl'],
 'consistency_edges_12_89_100.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_12_89_12.pkl': ['umap_edges_1_2_0.0_pca.pkl'],
 'consistency_edges_12_89_23.pkl': ['umap_edges_1_2_0.0_pca.pkl'],
 'consistency_edges_12_89_34.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_12_89_45.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_12_89_56.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_12_89_67.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_12_89_78.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_12_89_89.pkl': ['umap_edges_12_13_0.0_spectral.pkl'],
 'consistency_edges_1_100_1.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_100_100.pkl': ['umap_edges_1_2_0.25_spectral.pkl'],
 'consistency_edges_1_100_12.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_100_23.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_1_100_34.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_1_100_45.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_1_100_56.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_1_100_67.pkl': ['umap_edges_1_2_0.25_spectral.pkl'],
 'consistency_edges_1_100_78.pkl': ['umap_edges_1_2_0.25_spectral.pkl'],
 'consistency_edges_1_100_89.pkl': ['umap_edges_1_2_0.25_spectral.pkl'],
 'consistency_edges_1_12_1.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_12_100.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_12_12.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_12_23.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_12_34.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_12_45.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_12_56.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_12_67.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_12_78.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_12_89.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_1_1.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_1_100.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_1_12.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_1_23.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_1_34.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_1_45.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_1_56.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_1_67.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_1_78.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_1_89.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_23_1.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_23_100.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_23_12.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_23_23.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_23_34.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_23_45.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_23_56.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_23_67.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_23_78.pkl': ['umap_edges_1_2_0.25_spectral.pkl'],
 'consistency_edges_1_23_89.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_34_1.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_34_100.pkl': ['umap_edges_1_2_0.25_spectral.pkl'],
 'consistency_edges_1_34_12.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_34_23.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_34_34.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_34_45.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_34_56.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_34_67.pkl': ['umap_edges_1_2_0.25_spectral.pkl'],
 'consistency_edges_1_34_78.pkl': ['umap_edges_1_2_0.25_spectral.pkl'],
 'consistency_edges_1_34_89.pkl': ['umap_edges_1_2_0.25_spectral.pkl'],
 'consistency_edges_1_45_1.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_45_100.pkl': ['umap_edges_1_2_0.25_spectral.pkl'],
 'consistency_edges_1_45_12.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_45_23.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_45_34.pkl': ['umap_edges_1_2_0.25_spectral.pkl'],
 'consistency_edges_1_45_45.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_45_56.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_1_45_67.pkl': ['umap_edges_1_2_0.25_spectral.pkl'],
 'consistency_edges_1_45_78.pkl': ['umap_edges_1_2_0.25_spectral.pkl'],
 'consistency_edges_1_45_89.pkl': ['umap_edges_1_2_0.25_spectral.pkl'],
 'consistency_edges_1_56_1.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_56_100.pkl': ['umap_edges_1_2_0.25_spectral.pkl'],
 'consistency_edges_1_56_12.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_56_23.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_56_34.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_56_45.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_56_56.pkl': ['umap_edges_1_2_0.0_spectral.pkl'],
 'consistency_edges_1_56_67.pkl': ['umap_edges_1_2_0.25_spectral.pkl'],
 'consistency_edges_1_56_78.pkl': ['umap_edges_1_2_0.25_spectral.pkl'],
 'consistency_edges_1_56_89.pkl': ['umap_edges_1_2_0.25_spectral.pkl'],
 'consistency_edges_1_67_1.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_67_100.pkl': ['umap_edges_1_2_0.25_spectral.pkl'],
 'consistency_edges_1_67_12.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_67_23.pkl': ['umap_edges_1_2_0.25_pca.pkl'],
 'consistency_edges_1_67_34.pkl': ['umap_edges_1_2_0.25_spectral.pkl'],
 'consistency_edges_1_67_45.pkl': ['umap_edges_1_2_0.25_spectral.pkl'],
 'consistency_edges_1_67_56.pkl': ['umap_edges_1_2_0.25_spectral.pkl'],
 'consistency_edges_1_67_67.pkl': ['umap_edges_1_2_0.25_spectral.pkl'],

In [60]:
winners

{'umap_edges_12_13_0.0_pca.pkl',
 'umap_edges_12_13_0.0_spectral.pkl',
 'umap_edges_1_2_0.0_pca.pkl',
 'umap_edges_1_2_0.0_spectral.pkl',
 'umap_edges_1_2_0.25_pca.pkl',
 'umap_edges_1_2_0.25_spectral.pkl'}

# Determinando o melhor método por diferença crítica

In [61]:
def get_highest_scores(method: np.ndarray, score: str='F1_score'):
  return method.loc[method.groupby("Reference Graph")[score].idxmax()].set_index('Reference Graph')

In [62]:
pca_highest_f1 = get_highest_scores(pca)
tsne_highest_f1 = get_highest_scores(tsne)
tsne_pca_highest_f1 = get_highest_scores(tsne_pca)
umap_highest_f1 = get_highest_scores(umap)

In [63]:
pca_results = pca_highest_f1[['F1_score']].copy()
tsne_results = tsne_highest_f1[['F1_score']].copy()
tsne_pca_results = tsne_pca_highest_f1[['F1_score']].copy()
umap_results = umap_highest_f1[['F1_score']].copy()

In [64]:
pca_results = pca_results.rename(columns={'F1_score':'pca'})
tsne_results = tsne_results.rename(columns={'F1_score':'tsne'})
tsne_pca_results = tsne_pca_results.rename(columns={'F1_score':'tsne+pca'})
umap_results = umap_results.rename(columns={'F1_score':'umap'})

In [65]:
results = pd.concat((pca_results, tsne_results,tsne_pca_results, umap_results), axis=1)

In [66]:
results

                                        pca      tsne  tsne+pca      umap
Reference Graph
consistency_edges_100_100_1.pkl    0.056981  0.100890  0.095709  0.060909
consistency_edges_100_100_100.pkl  0.062991  0.156984  0.150102  0.094015
consistency_edges_100_100_12.pkl   0.055533  0.112358  0.107093  0.063600
consistency_edges_100_100_23.pkl   0.056696  0.122943  0.117222  0.070058
consistency_edges_100_100_34.pkl   0.059520  0.132643  0.126834  0.077018
...                                     ...       ...       ...       ...
consistency_edges_89_89_45.pkl     0.062197  0.141318  0.134732  0.082402
consistency_edges_89_89_56.pkl     0.063475  0.147079  0.140730  0.086831
consistency_edges_89_89_67.pkl     0.064071  0.151436  0.144982  0.089937
consistency_edges_89_89_78.pkl     0.064724  0.155180  0.148652  0.093352
consistency_edges_89_89_89.pkl     0.065023  0.158294  0.151394  0.095680

[1000 rows x 4 columns]

In [67]:
from critdd import Diagram

# create a CD diagram from the Pandas DataFrame
diagram = Diagram(
    results.to_numpy(),
    treatment_names = results.columns,
    maximize_outcome = True
)

In [68]:
diagram.average_ranks

array([3.47, 1.  , 2.  , 3.53])