## Relevant packages

In [1]:
import pandas as pd         # data management
from pathlib import Path    # saving files

## Downloading data (with gdown)

In [2]:
# getting the data from google drive (can run for a little long, data has 2,4GB)
!gdown --quiet 104WLoNAy02-r7d18ZE16vudY0puVpxm2

Downloading...
From (original): https://drive.google.com/uc?id=104WLoNAy02-r7d18ZE16vudY0puVpxm2
From (redirected): https://drive.google.com/uc?id=104WLoNAy02-r7d18ZE16vudY0puVpxm2&confirm=t&uuid=7cc07d1c-0e98-49d9-8e7f-cd73cbc48619
To: c:\Users\vinic\OneDrive\Área de Trabalho\RL-COVID-EVENTS\data_steps\df_event_data_with_embeddings.pkl

  0%|          | 0.00/2.59G [00:00<?, ?B/s]
  0%|          | 524k/2.59G [00:00<22:40, 1.90MB/s]
  0%|          | 1.57M/2.59G [00:00<11:36, 3.72MB/s]
  0%|          | 2.10M/2.59G [00:00<10:32, 4.09MB/s]
  0%|          | 2.62M/2.59G [00:00<10:49, 3.99MB/s]
  0%|          | 3.15M/2.59G [00:00<10:06, 4.27MB/s]
  0%|          | 4.19M/2.59G [00:00<08:32, 5.05MB/s]
  0%|          | 5.24M/2.59G [00:01<08:48, 4.90MB/s]
  0%|          | 5.77M/2.59G [00:01<09:05, 4.74MB/s]
  0%|          | 6.82M/2.59G [00:01<08:35, 5.01MB/s]
  0%|          | 7.34M/2.59G [00:01<09:07, 4.72MB/s]
  0%|          | 7.86M/2.59G [00:01<09:41, 4.44MB/s]
  0%|          | 8.39M/2.59G [00:01<09:51, 4.36MB/s]
  0%|          | 8.91M/2.59G [00:02<09:40, 4.45MB/s]
  0%|          | 9.44M/2.59G [00:02<10:42, 4.01MB/s]
  0%|          | 9.96M/2.59G [00:02<10:25, 4.12MB/s]
  0%|          | 10.5M/2.59G [00:02<09:47, 4.39MB/s]
  0%|          | 11.0M/2.59G [00:02<09:40, 4.45MB/s]
  0%|          | 11.5M/2.59G [00:02<09:50, 4.37MB/s]
  0%|          | 12.1M/2.59G [00:02<09:51, 4.36MB/s]
  0%|          | 12.6M/2.59G [00:02<10:25, 4.12MB/s]
  1%|          | 13.6M/2.59G [00:03<09:21, 4.59MB/s]
  1%|          | 14.2M/2.59G [00:03<09:06, 4.71MB/s]
  1%|          | 14.7M/2.59G [00:03<09:18, 4.61MB/s]
  1%|          | 15.7M/2.59G [00:03<09:02, 4.75MB/s]
  1%|          | 16.8M/2.59G [00:03<08:29, 5.05MB/s]
  1%|          | 17.8M/2.59G [00:03<08:29, 5.05MB/s]
  1%|          | 18.4M/2.59G [00:04<08:30, 5.03MB/s]
  1%|          | 19.4M/2.59G [00:04<08:10, 5.25MB/s]
  1%|          | 19.9M/2.59G [00:04<08:30, 5.03MB/s]
  1%|          | 21.0M/2.59G [00:04<08:18, 5.16MB/s]
  1%|          | 22.0M/2.59G [00:04<08:58, 4.77MB/s]
  1%|          | 22.5M/2.59G [00:04<09:01, 4.75MB/s]
  1%|          | 23.1M/2.59G [00:05<08:56, 4.79MB/s]
  1%|          | 23.6M/2.59G [00:05<09:28, 4.52MB/s]
  1%|          | 24.1M/2.59G [00:05<10:58, 3.90MB/s]
  1%|          | 24.6M/2.59G [00:05<11:54, 3.59MB/s]
  1%|          | 25.7M/2.59G [00:05<10:21, 4.13MB/s]
  1%|          | 26.7M/2.59G [00:05<09:40, 4.42MB/s]
  1%|          | 27.8M/2.59G [00:06<09:22, 4.56MB/s]
  1%|          | 28.8M/2.59G [00:06<08:37, 4.95MB/s]
  1%|          | 29.9M/2.59G [00:06<08:41, 4.91MB/s]
  1%|          | 30.9M/2.59G [00:06<08:16, 5.15MB/s]
  1%|          | 31.5M/2.59G [00:06<08:18, 5.14MB/s]
  1%|          | 32.0M/2.59G [00:06<08:27, 5.04MB/s]
  1%|▏         | 33.0M/2.59G [00:07<08:41, 4.90MB/s]
  1%|▏         | 34.1M/2.59G [00:07<08:18, 5.13MB/s]
  1%|▏         | 34.6M/2.59G [00:07<08:24, 5.07MB/s]
  1%|▏         | 35.7M/2.59G [00:07<07:56, 5.36MB/s]
  1%|▏         | 36.7M/2.59G [00:07<08:09, 5.22MB/s]
  1%|▏         | 37.2M/2.59G [00:07<08:20, 5.11MB/s]
  1%|▏         | 37.7M/2.59G [00:08<08:32, 4.98MB/s]
  1%|▏         | 38.3M/2.59G [00:08<08:30, 5.00MB/s]
  2%|▏         | 39.3M/2.59G [00:08<07:40, 5.54MB/s]
  2%|▏         | 40.4M/2.59G [00:08<08:05, 5.25MB/s]
  2%|▏         | 41.4M/2.59G [00:08<07:43, 5.50MB/s]
  2%|▏         | 42.5M/2.59G [00:08<08:34, 4.95MB/s]
  2%|▏         | 43.5M/2.59G [00:09<07:58, 5.32MB/s]
  2%|▏         | 44.6M/2.59G [00:09<08:05, 5.24MB/s]
  2%|▏         | 45.6M/2.59G [00:09<07:49, 5.43MB/s]
  2%|▏         | 46.7M/2.59G [00:09<08:02, 5.27MB/s]
  2%|▏         | 47.7M/2.59G [00:09<08:38, 4.90MB/s]
  2%|▏         | 48.8M/2.59G [00:10<07:56, 5.34MB/s]
  2%|▏         | 49.8M/2.59G [00:10<07:53, 5.36MB/s]
  2%|▏         | 50.9M/2.59G [00:10<07:46, 5.44MB/s]
  2%|▏         | 51.9M/2.59G [00:10<08:00, 5.29MB/s]
  2%|▏         | 53.0M/2.59G [00:10<07:49, 5.41MB/s]
  2%|▏         | 54.0M/2.59G [00:11<08:03, 5.25MB/s]
  2%|▏         | 55.1M/2.59G [00:11<07:47, 5.42MB/s]
  2%|▏         | 56.1M/2.59G [00:11<07:49, 5.40MB/s]
  2%|▏         | 57.1M/2.59G [00:11<08:01, 5.26MB/s]
  2%|▏         | 58.2M/2.59G [00:11<08:07, 5.19MB/s]
  2%|▏         | 58.7M/2.59G [00:12<08:46, 4.81MB/s]
  2%|▏         | 59.2M/2.59G [00:12<08:38, 4.88MB/s]
  2%|▏         | 59.8M/2.59G [00:12<09:19, 4.53MB/s]
  2%|▏         | 60.3M/2.59G [00:12<09:44, 4.33MB/s]
  2%|▏         | 61.3M/2.59G [00:12<08:57, 4.71MB/s]
  2%|▏         | 62.4M/2.59G [00:12<08:34, 4.92MB/s]
  2%|▏         | 62.9M/2.59G [00:12<08:55, 4.72MB/s]
  2%|▏         | 64.0M/2.59G [00:13<08:38, 4.87MB/s]
  2%|▏         | 64.5M/2.59G [00:13<08:43, 4.83MB/s]
  3%|▎         | 65.5M/2.59G [00:13<08:54, 4.73MB/s]
  3%|▎         | 66.1M/2.59G [00:13<08:48, 4.77MB/s]
  3%|▎         | 66.6M/2.59G [00:13<08:38, 4.86MB/s]
  3%|▎         | 67.1M/2.59G [00:13<10:41, 3.93MB/s]
  3%|▎         | 67.6M/2.59G [00:14<12:43, 3.30MB/s]
  3%|▎         | 68.2M/2.59G [00:14<12:38, 3.33MB/s]
  3%|▎         | 69.2M/2.59G [00:14<10:17, 4.08MB/s]
  3%|▎         | 70.3M/2.59G [00:14<08:47, 4.78MB/s]
  3%|▎         | 71.3M/2.59G [00:14<08:33, 4.90MB/s]
  3%|▎         | 71.8M/2.59G [00:15<10:28, 4.01MB/s]
  3%|▎         | 72.9M/2.59G [00:15<09:23, 4.47MB/s]
  3%|▎         | 73.9M/2.59G [00:15<08:28, 4.95MB/s]
  3%|▎         | 75.0M/2.59G [00:15<08:08, 5.15MB/s]
  3%|▎         | 76.0M/2.59G [00:15<07:50, 5.35MB/s]
  3%|▎         | 77.1M/2.59G [00:16<07:45, 5.40MB/s]
  3%|▎         | 78.1M/2.59G [00:16<07:51, 5.33MB/s]
  3%|▎         | 79.2M/2.59G [00:16<07:45, 5.40MB/s]
  3%|▎         | 80.2M/2.59G [00:16<07:55, 5.28MB/s]
  3%|▎         | 81.3M/2.59G [00:16<08:07, 5.15MB/s]
  3%|▎         | 81.8M/2.59G [00:16<08:08, 5.14MB/s]
  3%|▎         | 82.8M/2.59G [00:17<07:43, 5.41MB/s]
  3%|▎         | 83.9M/2.59G [00:17<07:33, 5.53MB/s]
  3%|▎         | 84.9M/2.59G [00:17<07:42, 5.42MB/s]
  3%|▎         | 86.0M/2.59G [00:17<07:50, 5.32MB/s]
  3%|▎         | 87.0M/2.59G [00:17<07:55, 5.26MB/s]
  3%|▎         | 88.1M/2.59G [00:18<07:55, 5.26MB/s]
  3%|▎         | 89.1M/2.59G [00:18<07:40, 5.44MB/s]
  3%|▎         | 90.2M/2.59G [00:18<07:49, 5.32MB/s]
  4%|▎         | 91.2M/2.59G [00:18<07:59, 5.21MB/s]
  4%|▎         | 92.3M/2.59G [00:18<07:43, 5.39MB/s]
  4%|▎         | 93.3M/2.59G [00:19<07:46, 5.36MB/s]
  4%|▎         | 94.4M/2.59G [00:19<08:30, 4.89MB/s]
  4%|▎         | 94.9M/2.59G [00:19<08:30, 4.89MB/s]
  4%|▎         | 95.9M/2.59G [00:19<08:30, 4.89MB/s]
  4%|▎         | 97.0M/2.59G [00:19<08:13, 5.05MB/s]
  4%|▍         | 98.0M/2.59G [00:20<08:02, 5.17MB/s]
  4%|▍         | 98.6M/2.59G [00:20<08:11, 5.07MB/s]
  4%|▍         | 99.1M/2.59G [00:20<08:11, 5.06MB/s]
  4%|▍         | 100M/2.59G [00:20<07:42, 5.38MB/s]
  4%|▍         | 101M/2.59G [00:20<07:37, 5.44MB/s]
  4%|▍         | 102M/2.59G [00:20<09:26, 4.39MB/s]
  4%|▍         | 103M/2.59G [00:21<09:44, 4.26MB/s]
  4%|▍         | 103M/2.59G [00:21<09:29, 4.37MB/s]
  4%|▍         | 104M/2.59G [00:21<09:27, 4.38MB/s]
  4%|▍         | 105M/2.59G [00:21<08:54, 4.65MB/s]
  4%|▍         | 106M/2.59G [00:21<08:20, 4.96MB/s]
  4%|▍         | 107M/2.59G [00:21<08:25, 4.91MB/s]
  4%|▍         | 107M/2.59G [00:22<09:18, 4.45MB/s]
  4%|▍         | 108M/2.59G [00:22<09:35, 4.31MB/s]
  4%|▍         | 109M/2.59G [00:22<09:14, 4.47MB/s]
  4%|▍         | 109M/2.59G [00:22<09:09, 4.52MB/s]
  4%|▍         | 110M/2.59G [00:22<09:02, 4.57MB/s]
  4%|▍         | 111M/2.59G [00:22<08:04, 5.12MB/s]
  4%|▍         | 112M/2.59G [00:22<07:17, 5.67MB/s]
  4%|▍         | 113M/2.59G [00:23<07:42, 5.36MB/s]
  4%|▍         | 114M/2.59G [00:23<08:00, 5.15MB/s]
  4%|▍         | 115M/2.59G [00:23<07:42, 5.35MB/s]
  4%|▍         | 116M/2.59G [00:23<07:39, 5.38MB/s]
  5%|▍         | 117M/2.59G [00:23<07:14, 5.69MB/s]
  5%|▍         | 118M/2.59G [00:24<07:23, 5.57MB/s]
  5%|▍         | 119M/2.59G [00:24<07:08, 5.76MB/s]
  5%|▍         | 120M/2.59G [00:24<07:01, 5.87MB/s]
  5%|▍         | 121M/2.59G [00:24<07:03, 5.82MB/s]
  5%|▍         | 122M/2.59G [00:24<06:57, 5.91MB/s]
  5%|▍         | 123M/2.59G [00:24<07:01, 5.85MB/s]
  5%|▍         | 124M/2.59G [00:25<07:01, 5.85MB/s]
  5%|▍         | 125M/2.59G [00:25<06:52, 5.98MB/s]
  5%|▍         | 126M/2.59G [00:25<06:32, 6.28MB/s]
  5%|▍         | 127M/2.59G [00:25<06:52, 5.97MB/s]
  5%|▍         | 128M/2.59G [00:25<06:54, 5.94MB/s]
  5%|▍         | 129M/2.59G [00:25<07:09, 5.73MB/s]
  5%|▌         | 131M/2.59G [00:26<06:52, 5.96MB/s]
  5%|▌         | 132M/2.59G [00:26<06:57, 5.89MB/s]
  5%|▌         | 133M/2.59G [00:26<06:54, 5.93MB/s]
  5%|▌         | 134M/2.59G [00:26<06:44, 6.08MB/s]
  5%|▌         | 135M/2.59G [00:26<06:44, 6.08MB/s]
  5%|▌         | 136M/2.59G [00:27<07:07, 5.74MB/s]
  5%|▌         | 137M/2.59G [00:27<06:55, 5.91MB/s]
  5%|▌         | 138M/2.59G [00:27<07:00, 5.83MB/s]
  5%|▌         | 139M/2.59G [00:27<06:48, 6.00MB/s]
  5%|▌         | 140M/2.59G [00:27<06:53, 5.93MB/s]
  5%|▌         | 141M/2.59G [00:27<07:29, 5.45MB/s]
  5%|▌         | 142M/2.59G [00:28<07:33, 5.40MB/s]
  6%|▌         | 143M/2.59G [00:28<07:33, 5.39MB/s]
  6%|▌         | 144M/2.59G [00:28<07:31, 5.42MB/s]
  6%|▌         | 145M/2.59G [00:28<07:25, 5.49MB/s]
  6%|▌         | 146M/2.59G [00:28<07:47, 5.23MB/s]
  6%|▌         | 147M/2.59G [00:29<09:05, 4.48MB/s]
  6%|▌         | 148M/2.59G [00:29<09:06, 4.47MB/s]
  6%|▌         | 149M/2.59G [00:29<08:23, 4.85MB/s]
  6%|▌         | 149M/2.59G [00:29<08:17, 4.91MB/s]
  6%|▌         | 150M/2.59G [00:29<08:10, 4.98MB/s]
  6%|▌         | 151M/2.59G [00:29<08:20, 4.87MB/s]
  6%|▌         | 152M/2.59G [00:30<07:32, 5.39MB/s]
  6%|▌         | 153M/2.59G [00:30<07:32, 5.38MB/s]
  6%|▌         | 154M/2.59G [00:30<07:40, 5.29MB/s]
  6%|▌         | 155M/2.59G [00:30<07:31, 5.39MB/s]
  6%|▌         | 156M/2.59G [00:30<07:40, 5.29MB/s]
  6%|▌         | 157M/2.59G [00:31<07:49, 5.19MB/s]
  6%|▌         | 158M/2.59G [00:31<07:34, 5.35MB/s]
  6%|▌         | 159M/2.59G [00:31<07:39, 5.29MB/s]
  6%|▌         | 160M/2.59G [00:31<07:31, 5.38MB/s]
  6%|▌         | 161M/2.59G [00:31<07:38, 5.30MB/s]
  6%|▋         | 163M/2.59G [00:32<07:47, 5.19MB/s]
  6%|▋         | 164M/2.59G [00:32<07:34, 5.35MB/s]
  6%|▋         | 165M/2.59G [00:32<07:02, 5.74MB/s]
  6%|▋         | 166M/2.59G [00:32<06:52, 5.87MB/s]
  6%|▋         | 167M/2.59G [00:32<06:56, 5.83MB/s]
  6%|▋         | 168M/2.59G [00:32<06:47, 5.94MB/s]
  7%|▋         | 169M/2.59G [00:33<07:02, 5.73MB/s]
  7%|▋         | 170M/2.59G [00:33<06:53, 5.86MB/s]
  7%|▋         | 171M/2.59G [00:33<06:51, 5.89MB/s]
  7%|▋         | 172M/2.59G [00:33<06:47, 5.94MB/s]
  7%|▋         | 173M/2.59G [00:33<06:57, 5.79MB/s]
  7%|▋         | 174M/2.59G [00:34<06:57, 5.79MB/s]
  7%|▋         | 175M/2.59G [00:34<08:29, 4.74MB/s]
  7%|▋         | 176M/2.59G [00:34<08:21, 4.82MB/s]
  7%|▋         | 177M/2.59G [00:34<07:51, 5.12MB/s]
  7%|▋         | 178M/2.59G [00:34<07:41, 5.23MB/s]
  7%|▋         | 179M/2.59G [00:35<07:19, 5.48MB/s]
  7%|▋         | 180M/2.59G [00:35<06:57, 5.77MB/s]
  7%|▋         | 181M/2.59G [00:35<06:44, 5.96MB/s]
  7%|▋         | 182M/2.59G [00:35<06:40, 6.01MB/s]
  7%|▋         | 183M/2.59G [00:35<06:49, 5.88MB/s]
  7%|▋         | 184M/2.59G [00:35<06:59, 5.73MB/s]
  7%|▋         | 185M/2.59G [00:36<06:45, 5.94MB/s]
  7%|▋         | 186M/2.59G [00:36<06:54, 5.80MB/s]
  7%|▋         | 187M/2.59G [00:36<07:38, 5.24MB/s]
  7%|▋         | 188M/2.59G [00:36<07:39, 5.23MB/s]
  7%|▋         | 189M/2.59G [00:36<07:35, 5.27MB/s]
  7%|▋         | 190M/2.59G [00:37<07:38, 5.23MB/s]
  7%|▋         | 191M/2.59G [00:37<07:36, 5.25MB/s]
  7%|▋         | 192M/2.59G [00:37<07:39, 5.22MB/s]
  7%|▋         | 193M/2.59G [00:37<07:40, 5.21MB/s]
  8%|▊         | 195M/2.59G [00:37<07:41, 5.19MB/s]
  8%|▊         | 196M/2.59G [00:38<07:15, 5.50MB/s]
  8%|▊         | 197M/2.59G [00:38<07:24, 5.39MB/s]
  8%|▊         | 198M/2.59G [00:38<07:21, 5.42MB/s]
  8%|▊         | 199M/2.59G [00:38<08:03, 4.95MB/s]
  8%|▊         | 200M/2.59G [00:38<07:45, 5.14MB/s]
  8%|▊         | 200M/2.59G [00:39<08:01, 4.96MB/s]
  8%|▊         | 201M/2.59G [00:39<08:00, 4.98MB/s]
  8%|▊         | 202M/2.59G [00:39<07:35, 5.24MB/s]
  8%|▊         | 203M/2.59G [00:39<07:15, 5.48MB/s]
  8%|▊         | 204M/2.59G [00:39<07:36, 5.22MB/s]
  8%|▊         | 205M/2.59G [00:39<07:25, 5.35MB/s]
  8%|▊         | 206M/2.59G [00:40<07:45, 5.12MB/s]
  8%|▊         | 207M/2.59G [00:40<07:39, 5.19MB/s]
  8%|▊         | 208M/2.59G [00:40<08:21, 4.75MB/s]
  8%|▊         | 208M/2.59G [00:40<09:40, 4.11MB/s]
  8%|▊         | 209M/2.59G [00:40<08:39, 4.59MB/s]
  8%|▊         | 210M/2.59G [00:41<08:24, 4.72MB/s]
  8%|▊         | 211M/2.59G [00:41<07:46, 5.10MB/s]
  8%|▊         | 212M/2.59G [00:41<07:40, 5.16MB/s]
  8%|▊         | 213M/2.59G [00:41<07:43, 5.13MB/s]
  8%|▊         | 214M/2.59G [00:41<07:10, 5.52MB/s]
  8%|▊         | 215M/2.59G [00:41<07:10, 5.52MB/s]
  8%|▊         | 216M/2.59G [00:42<07:08, 5.54MB/s]
  8%|▊         | 217M/2.59G [00:42<07:06, 5.56MB/s]
  8%|▊         | 218M/2.59G [00:42<06:55, 5.70MB/s]
  8%|▊         | 219M/2.59G [00:42<06:52, 5.75MB/s]
  8%|▊         | 220M/2.59G [00:42<06:59, 5.65MB/s]
  9%|▊         | 221M/2.59G [00:42<06:52, 5.74MB/s]
  9%|▊         | 222M/2.59G [00:43<06:40, 5.92MB/s]
  9%|▊         | 223M/2.59G [00:43<06:30, 6.06MB/s]
  9%|▊         | 224M/2.59G [00:43<06:26, 6.13MB/s]
  9%|▊         | 225M/2.59G [00:43<06:36, 5.96MB/s]
  9%|▊         | 226M/2.59G [00:43<06:50, 5.76MB/s]
  9%|▉         | 228M/2.59G [00:44<07:09, 5.50MB/s]
  9%|▉         | 229M/2.59G [00:44<06:50, 5.75MB/s]
  9%|▉         | 230M/2.59G [00:44<07:08, 5.51MB/s]
  9%|▉         | 231M/2.59G [00:44<07:03, 5.58MB/s]
  9%|▉         | 232M/2.59G [00:44<06:46, 5.81MB/s]
  9%|▉         | 233M/2.59G [00:45<07:16, 5.40MB/s]
  9%|▉         | 234M/2.59G [00:45<06:52, 5.71MB/s]
  9%|▉         | 235M/2.59G [00:45<06:51, 5.72MB/s]
  9%|▉         | 236M/2.59G [00:45<06:46, 5.79MB/s]
  9%|▉         | 237M/2.59G [00:45<07:21, 5.33MB/s]
  9%|▉         | 238M/2.59G [00:46<08:12, 4.78MB/s]
  9%|▉         | 239M/2.59G [00:46<08:06, 4.84MB/s]
  9%|▉         | 240M/2.59G [00:46<07:49, 5.01MB/s]
  9%|▉         | 241M/2.59G [00:46<07:13, 5.43MB/s]
  9%|▉         | 242M/2.59G [00:46<07:01, 5.57MB/s]
  9%|▉         | 243M/2.59G [00:46<06:57, 5.62MB/s]
  9%|▉         | 244M/2.59G [00:47<06:38, 5.89MB/s]
  9%|▉         | 245M/2.59G [00:47<06:35, 5.92MB/s]
  9%|▉         | 246M/2.59G [00:47<06:30, 6.01MB/s]
 10%|▉         | 247M/2.59G [00:47<06:21, 6.15MB/s]
 10%|▉         | 248M/2.59G [00:47<06:35, 5.92MB/s]
 10%|▉         | 249M/2.59G [00:47<06:34, 5.93MB/s]
 10%|▉         | 250M/2.59G [00:48<06:42, 5.82MB/s]
 10%|▉         | 251M/2.59G [00:48<06:48, 5.73MB/s]
 10%|▉         | 252M/2.59G [00:48<06:33, 5.95MB/s]
 10%|▉         | 253M/2.59G [00:48<06:22, 6.11MB/s]
 10%|▉         | 254M/2.59G [00:48<06:22, 6.11MB/s]
 10%|▉         | 255M/2.59G [00:48<06:26, 6.05MB/s]
 10%|▉         | 256M/2.59G [00:49<06:51, 5.68MB/s]
 10%|▉         | 257M/2.59G [00:49<06:43, 5.78MB/s]
 10%|▉         | 258M/2.59G [00:49<06:41, 5.81MB/s]
 10%|█         | 260M/2.59G [00:49<06:48, 5.70MB/s]
 10%|█         | 261M/2.59G [00:49<06:48, 5.71MB/s]
 10%|█         | 262M/2.59G [00:50<06:40, 5.82MB/s]
 10%|█         | 263M/2.59G [00:50<06:45, 5.74MB/s]
 10%|█         | 264M/2.59G [00:50<06:58, 5.55MB/s]
 10%|█         | 265M/2.59G [00:50<07:24, 5.24MB/s]
 10%|█         | 266M/2.59G [00:50<07:11, 5.38MB/s]
 10%|█         | 267M/2.59G [00:51<08:31, 4.54MB/s]
 10%|█         | 268M/2.59G [00:51<07:51, 4.93MB/s]
 10%|█         | 269M/2.59G [00:51<07:22, 5.25MB/s]
 10%|█         | 270M/2.59G [00:51<07:29, 5.17MB/s]
 10%|█         | 271M/2.59G [00:51<07:07, 5.43MB/s]
 11%|█         | 272M/2.59G [00:52<07:15, 5.33MB/s]
 11%|█         | 273M/2.59G [00:52<07:03, 5.47MB/s]
 11%|█         | 274M/2.59G [00:52<06:56, 5.56MB/s]
 11%|█         | 275M/2.59G [00:52<06:37, 5.83MB/s]
 11%|█         | 276M/2.59G [00:52<06:20, 6.08MB/s]
 11%|█         | 277M/2.59G [00:52<06:26, 5.99MB/s]
 11%|█         | 278M/2.59G [00:53<07:09, 5.39MB/s]
 11%|█         | 279M/2.59G [00:53<06:49, 5.64MB/s]
 11%|█         | 280M/2.59G [00:53<06:39, 5.78MB/s]
 11%|█         | 282M/2.59G [00:53<06:41, 5.75MB/s]
 11%|█         | 283M/2.59G [00:53<06:48, 5.65MB/s]
 11%|█         | 284M/2.59G [00:54<06:42, 5.73MB/s]
 11%|█         | 285M/2.59G [00:54<07:00, 5.49MB/s]
 11%|█         | 286M/2.59G [00:54<06:57, 5.52MB/s]
 11%|█         | 287M/2.59G [00:54<06:49, 5.63MB/s]
 11%|█         | 288M/2.59G [00:54<06:58, 5.50MB/s]
 11%|█         | 289M/2.59G [00:55<06:57, 5.52MB/s]
 11%|█         | 290M/2.59G [00:55<07:00, 5.47MB/s]
 11%|█         | 291M/2.59G [00:55<07:01, 5.45MB/s]
 11%|█▏        | 292M/2.59G [00:55<07:06, 5.38MB/s]
 11%|█▏        | 293M/2.59G [00:55<07:19, 5.23MB/s]
 11%|█▏        | 294M/2.59G [00:56<07:24, 5.17MB/s]
 11%|█▏        | 295M/2.59G [00:56<07:24, 5.16MB/s]
 11%|█▏        | 296M/2.59G [00:56<07:22, 5.18MB/s]
 11%|█▏        | 297M/2.59G [00:56<07:16, 5.26MB/s]
 12%|█▏        | 298M/2.59G [00:56<07:03, 5.41MB/s]
 12%|█▏        | 299M/2.59G [00:57<06:51, 5.57MB/s]
 12%|█▏        | 300M/2.59G [00:57<06:35, 5.79MB/s]
 12%|█▏        | 301M/2.59G [00:57<06:23, 5.97MB/s]
 12%|█▏        | 303M/2.59G [00:57<06:45, 5.64MB/s]
 12%|█▏        | 304M/2.59G [00:57<06:55, 5.51MB/s]
 12%|█▏        | 305M/2.59G [00:57<06:53, 5.52MB/s]
 12%|█▏        | 306M/2.59G [00:58<06:32, 5.81MB/s]
 12%|█▏        | 307M/2.59G [00:58<06:42, 5.68MB/s]
 12%|█▏        | 308M/2.59G [00:58<06:52, 5.53MB/s]
 12%|█▏        | 309M/2.59G [00:58<06:56, 5.48MB/s]
 12%|█▏        | 310M/2.59G [00:58<07:04, 5.37MB/s]
 12%|█▏        | 311M/2.59G [00:59<07:44, 4.91MB/s]
 12%|█▏        | 311M/2.59G [00:59<07:46, 4.89MB/s]
 12%|█▏        | 312M/2.59G [00:59<07:28, 5.08MB/s]
 12%|█▏        | 313M/2.59G [00:59<07:29, 5.07MB/s]
 12%|█▏        | 314M/2.59G [00:59<07:24, 5.12MB/s]
 12%|█▏        | 315M/2.59G [00:59<08:11, 4.63MB/s]
 12%|█▏        | 315M/2.59G [01:00<08:47, 4.31MB/s]
 12%|█▏        | 316M/2.59G [01:00<08:42, 4.36MB/s]
 12%|█▏        | 316M/2.59G [01:00<08:20, 4.54MB/s]
 12%|█▏        | 317M/2.59G [01:00<07:20, 5.16MB/s]
 12%|█▏        | 318M/2.59G [01:00<07:22, 5.14MB/s]
 12%|█▏        | 319M/2.59G [01:00<07:22, 5.13MB/s]
 12%|█▏        | 320M/2.59G [01:00<07:10, 5.28MB/s]
 12%|█▏        | 321M/2.59G [01:01<06:50, 5.53MB/s]
 12%|█▏        | 322M/2.59G [01:01<06:37, 5.71MB/s]
 12%|█▏        | 323M/2.59G [01:01<07:33, 5.00MB/s]
 12%|█▏        | 323M/2.59G [01:01<08:22, 4.51MB/s]
 13%|█▎        | 325M/2.59G [01:01<07:31, 5.02MB/s]
 13%|█▎        | 326M/2.59G [01:02<07:23, 5.10MB/s]
 13%|█▎        | 326M/2.59G [01:02<07:45, 4.87MB/s]
 13%|█▎        | 327M/2.59G [01:02<07:08, 5.28MB/s]
 13%|█▎        | 328M/2.59G [01:02<06:57, 5.42MB/s]
 13%|█▎        | 329M/2.59G [01:02<06:44, 5.59MB/s]
 13%|█▎        | 330M/2.59G [01:02<06:56, 5.43MB/s]
 13%|█▎        | 331M/2.59G [01:03<06:35, 5.71MB/s]
 13%|█▎        | 332M/2.59G [01:03<06:38, 5.67MB/s]
 13%|█▎        | 333M/2.59G [01:03<06:33, 5.73MB/s]
 13%|█▎        | 334M/2.59G [01:03<06:25, 5.86MB/s]
 13%|█▎        | 336M/2.59G [01:03<06:57, 5.41MB/s]
 13%|█▎        | 337M/2.59G [01:04<08:17, 4.53MB/s]
 13%|█▎        | 338M/2.59G [01:04<08:43, 4.30MB/s]
 13%|█▎        | 338M/2.59G [01:04<08:31, 4.41MB/s]
 13%|█▎        | 339M/2.59G [01:04<08:54, 4.21MB/s]
 13%|█▎        | 339M/2.59G [01:04<09:20, 4.02MB/s]
 13%|█▎        | 340M/2.59G [01:05<09:50, 3.81MB/s]
 13%|█▎        | 340M/2.59G [01:05<09:39, 3.88MB/s]
 13%|█▎        | 341M/2.59G [01:05<10:12, 3.68MB/s]
 13%|█▎        | 341M/2.59G [01:05<10:46, 3.48MB/s]
 13%|█▎        | 342M/2.59G [01:05<10:12, 3.67MB/s]
 13%|█▎        | 342M/2.59G [01:05<09:42, 3.86MB/s]
 13%|█▎        | 343M/2.59G [01:05<10:13, 3.67MB/s]
 13%|█▎        | 343M/2.59G [01:06<10:23, 3.61MB/s]
 13%|█▎        | 344M/2.59G [01:06<09:43, 3.85MB/s]
 13%|█▎        | 344M/2.59G [01:06<09:08, 4.10MB/s]
 13%|█▎        | 345M/2.59G [01:06<09:02, 4.14MB/s]
 13%|█▎        | 346M/2.59G [01:06<09:30, 3.94MB/s]

## Instanciate a dataframe

In [3]:
df_event_data = pd.read_pickle("df_event_data_with_embeddings.pkl")

In [4]:
df_event_data #run if you want to visualize the dataframe

,gid,url,geoinfo1,taxon1,taxon2,geoinfo2,who1,who2,text,predict,predict_proba,country,country_code,country_lat,country_lng,embeddings
924124,20200214223000-56,https://www.hppr.org/post/how-covid-19-kills-n...,,KILL;CRISISLEX_T03_DEAD;TAX_DISEASE;TAX_DISEAS...,"CRISISLEX_CRISISLEXREC,3366;TAX_DISEASE_INFECT...","4#Wuhan, Hubei, China#CH#CH12#13124#30.5833#11...","Anthony Fauci,3509;Yoko Furuya,1354;Sylvie Bri...","Columbia University Irving Medical Center,1434...",How COVID-19 Kills: The New Coronavirus Diseas...,covid-19 vaccine,1.000000,"Wuhan, Hubei, China",CH,30.5833,114.267,"[-0.020972056, -0.12172927, -0.007201001, -0.0..."
2284004,20200228053000-1137,http://www.ecns.cn/news/politics/2020-02-28/de...,KILL#13##1#South Korea#KS#KS#37#127.5#KS#2101;...,TAX_ETHNICITY;TAX_ETHNICITY_CHINESE;TAX_WORLDL...,"TAX_DISEASE_EPIDEMIC,1288;TAX_DISEASE_EPIDEMIC...",1#South Korea#KS#KS##37#127.5#KS#33;1#South Ko...,"Xing Haiming,46;Xing Haiming,240;Xing Haiming,...","Chinese Embassy,157;Chinese Embassy,351;Chines...",Chinese Embassy in South Korea donates masks t...,funding for covid,1.000000,South Korea,KS,37,127.5,"[0.05996564, -0.16531578, -0.0031238094, 0.057..."
1181064,20200224034500-218,https://www.rnz.co.nz/news/national/410233/cov...,,TAX_FNCACT;TAX_FNCACT_MINISTER;LEADER;TAX_FNCA...,"CRISISLEX_CRISISLEXREC,1466;UNGP_HEALTHCARE,74...",1#South Korea#KS#KS##37#127.5#KS#1508;1#Chines...,"Jacinda Arden,28","World Health Organisation,1182",Covid-19: Travel restrictions for those coming...,covid-19 restrictions lifted,1.000000,South Korea,KS,37,127.5,"[-0.104065694, 0.03418176, -0.0051460676, -0.0..."
3572684,20200224134500-9,https://www.chinanationalnews.com/news/2641216...,KILL#150##1#China#CH#CH#35#105#CH#1919;KILL#2#...,TAX_ETHNICITY;TAX_ETHNICITY_INDIAN;TAX_FNCACT;...,"GENERAL_HEALTH,1852;MEDICAL,1852;GENERAL_GOVER...",1#South Korea#KS#KS##37#127.5#KS#18;1#South Ko...,,"South China Morning Post,1835;Yonhap News Agen...","COVID-19: Reconsider travelling to S Korea, In...",hospital for covid-19 patients,0.333333,South Korea,KS,37,127.5,"[-0.043811183, -0.0037411905, -0.005606968, 0...."
3188350,20200224071500-424,https://www.thenorthernecho.co.uk/news/nationa...,KILL#2##1#China#CH#CH#35#105#CH#134;KILL#8##1#...,KILL;TAX_FNCACT;TAX_FNCACT_OFFICIALS;TAX_DISEA...,"GENERAL_GOVERNMENT,2051;EPU_POLICY_GOVERNMENT,...","4#Milan, Lombardia, Italy#IT#IT09#18363#45.466...",,"Xinhua News Agency,1731;Xinhua,1719;Xinhua,1798",South Korea sees increase in recorded Covid-19...,covid-19 cases emerge,0.666667,"Milan, Lombardia, Italy",IT,45.4667,9.2,"[-0.026586916, -0.3584028, -0.0059149084, -0.0..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1029937,20210309233000-1970,https://www.tbnewswatch.com/local-news/thunder...,,SECURITY_SERVICES;TAX_FNCACT;TAX_FNCACT_POLICE...,"MEDICAL,768;MEDICAL,1151;TAX_FNCACT_PARAMEDICS...","4#Thunder Bay, Ontario, Canada#CA#CA08#12684#4...","Bill Mauro,1354;Kristen Oliver,153",,Thunder Bay frontline officers receive first d...,covid-19 vaccine,1.000000,"Thunder Bay, Ontario, Canada",CA,48.4,-89.2333,"[-0.074297085, -0.2056211, -0.0043920088, -0.1..."
180173,20210308140000-411,https://www.ross-shirejournal.co.uk/news/ross-...,,TAX_FNCACT;TAX_FNCACT_WOMEN;EPU_ECONOMY;EPU_EC...,"GENERAL_GOVERNMENT,1355;EPU_POLICY_GOVERNMENT,...",1#Scotland#UK#UK##54#-4#UK#428;1#Scotland#UK#U...,"Maree Todd,24","Scottish Government Women Returners Programme,...",Women have suffered 'disproportionately' from ...,impact of the covid-19,1.000000,Scotland,UK,54,-4,"[-0.10385181, 0.0008548315, -0.0063411416, -0...."
703959,20210302051500-673,https://www.republicworld.com/world-news/pakis...,KILL#896##1#Pakistan#PK#PK#30#70#PK#647;,GENERAL_HEALTH;MEDICAL;TAX_DISEASE;TAX_DISEASE...,"GENERAL_GOVERNMENT,1807;GENERAL_GOVERNMENT,216...",1#Pakistani#PK#PK##30#70#PK#141;1#Pakistan#PK#...,"Qaisar Sajjad,1518","Pakistan National,689;Pakistan Medical Associa...",Pakistan's NCOC raises alarm over dull vaccine...,covid-19 vaccine,1.000000,Pakistani,PK,30,70,"[0.018137967, 0.01642545, -0.0037686664, -0.07..."
2108475,20210520121500-755,https://www.shanghainews.net/news/269559138/un...,,TAX_FNCACT;TAX_FNCACT_OFFICIALS;GENERAL_HEALTH...,"MEDICAL,992;GENERAL_HEALTH,603;HEALTH_VACCINAT...","2#Illinois, United States#US#USIL##40.3363#-89...",,"United Airlines,79;United Airlines,942;Moody,5...",United Airlines adding flights worldwide as Co...,covid-19 restrictions eased,0.666667,"Illinois, United States",US,40.3363,-89.0022,"[-0.07282667, 0.09720857, -0.0031480393, -0.07..."
486543,20210323164500-1265,https://www.penarthtimes.co.uk/news/19180604.v...,"KILL#2000##4#Glamorgan, Neath Port Talbot, Uni...",TAX_DISEASE;TAX_DISEASE_CORONAVIRUS;MANMADE_DI...,"HEALTH_VACCINATION,1435;TAX_FNCACT_DIRECTOR,18...","4#Glamorgan, Neath Port Talbot, United Kingdom...","Rob Thomas,1748;Cllr Neil Moore,884","National Covid Memorial Day,129",Vale of Glamorgan council marks National Covid...,covid-19 vaccine,0.666667,"Glamorgan, Neath Port Talbot, United Kingdom",UK,51.6667,-3.66667,"[-0.13808578, 0.0034517844, -0.010519803, 0.06..."

In [5]:
# getting the relevant columns (.copy to avoid a view)
df_relevant_columns = df_event_data[["gid","text","predict","country_lat","country_lng","embeddings"]].copy()

In [6]:
df_relevant_columns

,gid,text,predict,country_lat,country_lng,embeddings
924124,20200214223000-56,How COVID-19 Kills: The New Coronavirus Diseas...,covid-19 vaccine,30.5833,114.267,"[-0.020972056, -0.12172927, -0.007201001, -0.0..."
2284004,20200228053000-1137,Chinese Embassy in South Korea donates masks t...,funding for covid,37,127.5,"[0.05996564, -0.16531578, -0.0031238094, 0.057..."
1181064,20200224034500-218,Covid-19: Travel restrictions for those coming...,covid-19 restrictions lifted,37,127.5,"[-0.104065694, 0.03418176, -0.0051460676, -0.0..."
3572684,20200224134500-9,"COVID-19: Reconsider travelling to S Korea, In...",hospital for covid-19 patients,37,127.5,"[-0.043811183, -0.0037411905, -0.005606968, 0...."
3188350,20200224071500-424,South Korea sees increase in recorded Covid-19...,covid-19 cases emerge,45.4667,9.2,"[-0.026586916, -0.3584028, -0.0059149084, -0.0..."
...,...,...,...,...,...,...
1029937,20210309233000-1970,Thunder Bay frontline officers receive first d...,covid-19 vaccine,48.4,-89.2333,"[-0.074297085, -0.2056211, -0.0043920088, -0.1..."
180173,20210308140000-411,Women have suffered 'disproportionately' from ...,impact of the covid-19,54,-4,"[-0.10385181, 0.0008548315, -0.0063411416, -0...."
703959,20210302051500-673,Pakistan's NCOC raises alarm over dull vaccine...,covid-19 vaccine,30,70,"[0.018137967, 0.01642545, -0.0037686664, -0.07..."
2108475,20210520121500-755,United Airlines adding flights worldwide as Co...,covid-19 restrictions eased,40.3363,-89.0022,"[-0.07282667, 0.09720857, -0.0031480393, -0.07..."
486543,20210323164500-1265,Vale of Glamorgan council marks National Covid...,covid-19 vaccine,51.6667,-3.66667,"[-0.13808578, 0.0034517844, -0.010519803, 0.06..."

## Pre-processing data

In [7]:
# verifying the data types for each column
df_relevant_columns.info()

<class 'pandas.core.frame.DataFrame'>
Index: 392105 entries, 924124 to 486543
Data columns (total 6 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   gid          392105 non-null  object
 1   text         392105 non-null  object
 2   predict      392105 non-null  object
 3   country_lat  392105 non-null  object
 4   country_lng  392105 non-null  object
 5   embeddings   392105 non-null  object
dtypes: object(6)
memory usage: 20.9+ MB

In [8]:
# transforming the latitude and longitude in float type to allow oerations
df_relevant_columns['country_lat'] = pd.to_numeric(df_relevant_columns['country_lat'])
df_relevant_columns['country_lng'] = pd.to_numeric(df_relevant_columns['country_lng'])

In [9]:
# dropping data without geoespatial coordinates
df_relevant_columns = df_relevant_columns.dropna(subset={'country_lat','country_lng'})

In [19]:
# getting the dates from the gID 
dates = [date[:4]+'-'+date[4:6]+'-'+date[6:8] for date in df_relevant_columns.gid]
df_relevant_columns.loc[:, 'dates'] = pd.to_datetime(dates, errors='coerce')

In [20]:
df_relevant_columns.info() # just to see wheter or not changes were successful

<class 'pandas.core.frame.DataFrame'>
Index: 336195 entries, 924124 to 486543
Data columns (total 7 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   gid          336195 non-null  object
 1   text         336195 non-null  object
 2   predict      336195 non-null  object
 3   country_lat  336195 non-null  float64
 4   country_lng  336195 non-null  float64
 5   embeddings   336195 non-null  object
 6   dates        336195 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(4)
memory usage: 20.5+ MB

In [23]:
df_relevant_columns

,gid,text,predict,country_lat,country_lng,embeddings,dates
924124,20200214223000-56,How COVID-19 Kills: The New Coronavirus Diseas...,covid-19 vaccine,30.5833,114.26700,"[-0.020972056, -0.12172927, -0.007201001, -0.0...",2020-02-14
2284004,20200228053000-1137,Chinese Embassy in South Korea donates masks t...,funding for covid,37.0000,127.50000,"[0.05996564, -0.16531578, -0.0031238094, 0.057...",2020-02-28
1181064,20200224034500-218,Covid-19: Travel restrictions for those coming...,covid-19 restrictions lifted,37.0000,127.50000,"[-0.104065694, 0.03418176, -0.0051460676, -0.0...",2020-02-24
3572684,20200224134500-9,"COVID-19: Reconsider travelling to S Korea, In...",hospital for covid-19 patients,37.0000,127.50000,"[-0.043811183, -0.0037411905, -0.005606968, 0....",2020-02-24
3188350,20200224071500-424,South Korea sees increase in recorded Covid-19...,covid-19 cases emerge,45.4667,9.20000,"[-0.026586916, -0.3584028, -0.0059149084, -0.0...",2020-02-24
...,...,...,...,...,...,...,...
1029937,20210309233000-1970,Thunder Bay frontline officers receive first d...,covid-19 vaccine,48.4000,-89.23330,"[-0.074297085, -0.2056211, -0.0043920088, -0.1...",2021-03-09
180173,20210308140000-411,Women have suffered 'disproportionately' from ...,impact of the covid-19,54.0000,-4.00000,"[-0.10385181, 0.0008548315, -0.0063411416, -0....",2021-03-08
703959,20210302051500-673,Pakistan's NCOC raises alarm over dull vaccine...,covid-19 vaccine,30.0000,70.00000,"[0.018137967, 0.01642545, -0.0037686664, -0.07...",2021-03-02
2108475,20210520121500-755,United Airlines adding flights worldwide as Co...,covid-19 restrictions eased,40.3363,-89.00220,"[-0.07282667, 0.09720857, -0.0031480393, -0.07...",2021-05-20
486543,20210323164500-1265,Vale of Glamorgan council marks National Covid...,covid-19 vaccine,51.6667,-3.66667,"[-0.13808578, 0.0034517844, -0.010519803, 0.06...",2021-03-23

## Sampling to create datasets

In [13]:
# analyzing the amount of occurences for each label
df_relevant_columns['predict'].value_counts()

predict
covid-19 vaccine                   69975
 warned of covid-19                60502
 new covid-19 cases                31455
 deaths from covid-19              29308
 hospital for covid-19 patients    27199
covid-19 cases emerge              26270
 funding for covid                 23751
 tests for covid-19                21432
 covid-19 restrictions lifted       9182
 drug against covid-19              7302
 impact of the covid-19             6684
 covid-19 restrictions eased        5287
 treatments for covid-19            4130
 response to covid-19               2672
 reopening schools                  2087
 resurgence of covid-19             1592
 market analysis                    1185
 enforcing covid-19 protocols       1123
 breach covid rules                 1078
 festival cancelled                  997
 wears face mask                     898
 social distancing                   557
 quarantine for infected             470
 donate blood plasma                 387
researchers / science                318
covid drops to lowest                169
employers                            115
covid testing                         43
 granted emergency use                27
Name: count, dtype: int64

In [14]:
# selecting only the labels with more than 1000 occurrences as they are more significant to our purposes

label_counts = df_relevant_columns['predict'].value_counts()
predicts = df_relevant_columns['predict'].unique()

labels = [label for label in predicts if label_counts[label] > 1000]

In [15]:
len(labels)

19

In [16]:
# formatting them to save files 
def formatting_label_name(str: str) -> str:
  return str.title().replace(" ","")

In [17]:
size_limit = 10000 # maximum amount of rows for datasets, since some labels have many instances
rnd_state = 42 # ensures the same sample for the same data

# creates a path for the datasets
output_dir = "./resultant_datasets/"
Path(output_dir).mkdir(parents=True, exist_ok=True)


# samples the data
# if a label has more than num_rows instances, it returns a random sample of `num_rows` instances
def create_datasets(data: pd.DataFrame, label: str, num_rows: int = size_limit, random_state: int = 42) -> pd.DataFrame:
    dataset = data[data['predict'] == label]
    return dataset.sample(num_rows, random_state=random_state) if len(dataset) > num_rows else dataset

In [18]:
for label in labels:
  dataset = create_datasets(df_relevant_columns, label, size_limit, rnd_state)
  print(dataset.shape)
  dataset.to_pickle(f"{output_dir}/{formatting_label_name(label)}_dataset.pkl")

(10000, 7)
(10000, 7)
(9182, 7)
(10000, 7)
(10000, 7)
(10000, 7)
(10000, 7)
(10000, 7)
(10000, 7)
(4130, 7)
(7302, 7)
(5287, 7)
(6684, 7)
(2672, 7)
(1592, 7)
(1123, 7)
(1078, 7)
(1185, 7)
(2087, 7)

Another approach could be filter datasets without considering labels. Just getting a defined amount of instances of the dataset, regardless its label...